### ISSUE TITLE
SVC / CNVKIT Parallelization 

### ISSUE THREAD

**Issue by lsturm1** [bcbio/bcbio-nextgen#1582]
Hi,

Thanks for the help getting the svc tests to run and work. I got it to successfully complete on samples using cnvkit. However, it takes a very long time. During the detect_sv stage, bcbio fires up an array of engine computing nodes like it usually does, however it seems as though only one of the engines is actually doing anything. The others are just sitting there doing nothing. Is there some way to fix this? Let me know if you need any more information. 

Thank you,
Luke

**Comment by chapmanb** [comment]
Luke -- thanks for the feedback. We're actively working on moving CNVkit coverage calculation to be more efficient and run as part of the original coverage calculation. You can see #1549 for the discussion and work in progress. Sorry about the issues as we work through ways to improve this.

**Comment by lsturm1** [comment]
Thanks for a response! I kind of understand. Does taking 24 hours to do 10 samples seem like what you would expect? I'm still a bit confused why only one engine is doing something at this stage. It seems like for each sample, the cnvkit tool calculation should be independent of the other samples, so it would be able to work on n samples at a time, where n is the number of engines. This is how alignment works: there are ten engines and ten samples can be aligned all at once. Just trying to clarify to make sure I'm not doing anything wrong that is making it take so long. Thank you.

**Comment by chapmanb** [comment]
Luke -- do you mean that a single compute node is running and everything else is idle? That's unexpected. Sorry I misunderstood and thought it was about core usage on a node versus distribution over multiple nodes. Is it possible the other samples finished and it's working on one remaining one, or is this the behavior with a fresh run? It might be useful to see what bcbio-nextgen-debug.log looks like near when things are parallelizing poorly to see if we can spot the issue if that's not it. Hope this helps.

**Comment by lsturm1** [comment]
Hi Brad. So the cnvkit appears to have a couple of stages. Firs there is a pre alignment and alignment. Both of those parallelize perfect. The second cnvkit starts to fill in the structural directory, the problem starts. Only one compute node will do anything; all the rest are idle like you said. I have tried it many times, and it that happens every time.  This is when it starts making the -dedup-0.targetcoverage.cnn files and continues on after that. There are no 'errors' in any of the logs. After the dedup files are made there is a process that takes a very long time: 
[2016-10-03T15:52Z] sh-0-7.local: CNVkit fix
[2016-10-03T15:52Z] sh-0-7.local: Processing target: 03_22-dedup
[2016-10-03T15:53Z] sh-0-7.local: Keeping 1870766 of 2475767 bins
[2016-10-03T15:53Z] sh-0-7.local: Correcting for GC bias...
[2016-10-03T15:53Z] sh-0-7.local: Correcting for density bias...
[2016-10-03T15:53Z] sh-0-7.local: Processing antitarget: 03_22-dedup
[2016-10-03T15:54Z] sh-0-7.local: Wrote /local-scratch/lsturm/10025321/bcbiotx/c95d16ca-afcd-42ed-a999-5098cbe126ae/tmpOLeGe7/03_22-dedu\
p.cnr with 1870766 regions
[2016-10-03T15:54Z] sh-0-7.local: CNVkit segment
[2016-10-03T15:54Z] sh-0-7.local: Dropped 3456 outlier bins:
[2016-10-03T15:54Z] sh-0-7.local:    chromosome     start       end           gene     log2  depth    weight
[2016-10-03T15:54Z] sh-0-7.local: 0           1   1039045   1039278       C1orf159 -20.4036    0.0  0.147322
[2016-10-03T15:54Z] sh-0-7.local: 1           1   1312971   1313364    RP5-890O3.3 -19.7061    0.0  0.229711
[2016-10-03T15:54Z] sh-0-7.local: 2           1   1441852   1442121         ATAD3A -20.8506    0.0  0.256985
[2016-10-03T15:54Z] sh-0-7.local: 3           1   1886089   1886310       C1orf222 -21.1129    0.0  0.125634
[2016-10-03T15:54Z] sh-0-7.local: 4           1   1994858   1995100          PRKCZ -21.5981    0.0  0.394638
[2016-10-03T15:54Z] sh-0-7.local: 5           1   2251695   2251716          MORN1 -21.2462    0.0  0.084898
[2016-10-03T15:54Z] sh-0-7.local: 6           1   3399068   3399251       ARHGEF16 -21.3290    0.0  0.187698
[2016-10-03T15:54Z] sh-0-7.local: 7           1   6061590   6061813         KCNAB2 -21.2794    0.0  0.358464
[2016-10-03T15:54Z] sh-0-7.local: 8           1   6368318   6368448          ACOT7 -21.3758    0.0  0.393380
[2016-10-03T15:54Z] sh-0-7.local: 9           1   6492248   6492446           ESPN -21.8917    0.0  0.277944
[2016-10-03T15:54Z] sh-0-7.local: 10          1   6613029   6613296           NOL9 -21.1577    0.0  0.394181
[2016-10-03T15:54Z] sh-0-7.local: 11          1   8271538   8271674  RP11-431K24.3 -21.4266    0.0  0.416070
[2016-10-03T15:54Z] sh-0-7.local: 12          1   8402739   8402889        SLC45A1 -21.0107    0.0  0.176264
[2016-10-03T15:54Z] sh-0-7.local: 13          1   8521673   8521845           RERE -21.2213    0.0  0.331006
[2016-10-03T15:54Z] sh-0-7.local: 14          1   9126583   9126827         SLC2A5 -20.3015    0.0  0.386099
[2016-10-03T15:54Z] sh-0-7.local: 15          1   9866083   9866387         CLSTN1 -20.4954    0.0  0.474021
[2016-10-03T15:54Z] sh-0-7.local: 16          1  10214974  10215255          UBE4B -20.0910    0.0  0.163019
[2016-10-03T15:54Z] sh-0-7.local: 17          1  10391017  10391226          KIF1B -21.3953    0.0  0.449161
[2016-10-03T15:54Z] sh-0-7.local: 18          1  11077621  11077895         TARDBP -22.6548    0.0  0.457547
[2016-10-03T15:54Z] sh-0-7.local: 19          1  11171947  11172174           MTOR -20.6815    0.0  0.560245
[2016-10-03T15:54Z] sh-0-7.local: ...
[2016-10-03T15:57Z] sh-0-7.local: Wrote /local-scratch/lsturm/10025321/bcbiotx/3a30193e-3930-43c1-8cba-2504b172d77e/tmpn_6w0q/03_22-dedu\
p.cns with 126 regions

During this stage only one compute node is running too. The tool is still usable, but it takes a very long time to do a few samples. Do you have any idea why most of the compute nodes are idle? Is there something specific I could give you from the debug log.

Cheers,
Luke

**Comment by chapmanb** [comment]
Luke;
Thanks for the additional details. Which version of bcbio are you running? If it's not the latest development could you try updating to that `bcbio_nextgen.py -u development`. We recently added a fix which improves resource usage at this step by better allocating cores:

https://github.com/chapmanb/bcbio-nextgen/commit/c7fb6ead93f7a8b24cb4b85633a8466f66d52184

I hope this will result in more than one parallelization engine spinning up and better use of total cores.

If you're still having issues, it would be useful to see more of the log. You could add as a gist (https://gist.github.com/). It would specifically be useful to see the `Resource request` and following lines prior to the structural variant calling so we can understand what bcbio is trying to allocate and why. Thanks much for the help debugging.

**Comment by lsturm1** [comment]
I think the problem might be the problem: 
[2016-10-03T03:35Z] sh-0-7.local: Resource requests: cnvkit; memory: 3.00; cores: 16
[2016-10-03T03:35Z] sh-0-7.local: Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2016-10-03T03:35Z] sh-0-7.local: CNVkit coverage
[2016-10-03T03:35Z] sh-0-7.local: Processing reads in 03_20-dedup.bam
[2016-10-03T03:36Z] sh-0-7.local: Time: 42.087 seconds (40379 reads/sec, 2376 bins/sec)
[2016-10-03T03:36Z] sh-0-7.local: Summary: #bins=100000, #reads=1699421, mean=16.9942, min=0.0, max=748.08
[2016-10-03T03:36Z] sh-0-7.local: Percent reads in regions: 5.056 (of 33610841 mapped)
[2016-10-03T03:36Z] sh-0-7.local: Wrote /local-scratch/lsturm/10025321/bcbiotx/427373ba-e8c2-43d6-87fb-d77523f0bb01/tmpD0a93\
x/03_20-dedup-0.targetcoverage.cnn with 100000 regions

Only one job got configured. Does this help?

**Comment by chapmanb** [comment]
Luke -- thanks, this is definitely the source of the issue with running on a single core. It's a bit hard to diagnose what is causing it though. A couple of thoughts:

- Are you updated to the latest development version with the fix mentioned above?
- How many samples are in your input file?

I hope a multisample input file with the latest development version will do the right thing for you.

**Comment by lsturm1** [comment]
I updated to the latest development version, and it still is only requesting one job at that stage. In my config file, I am doing 10 samples. I have the 10 different algorithm sections doing svcaller: [cnvkit], each with their one associated data file to their BAM. Should I be doing it differently?

**Comment by chapmanb** [comment]
Luke -- I'm at a bit of a loss of what to suggest. You're doing everything right and it seems like it should spin up more nodes here. I've been trying to reproduce this without success. All I can think of is that you could send me your sample YAML either as a gist or via e-mail, and also the command you use to run bcbio. I can try to see if I can spot anything from that. Sorry to not have more of an idea of what is wrong.

**Comment by lsturm1** [comment]
Thanks so much for sticking with me to to try to find a solution! 

Here is the gist: https://gist.github.com/lsturm1/a90267d91c18fa7855fd02dee851dc84
Hopefully it is something silly.

**Comment by chapmanb** [comment]
Luke;
Thanks for posting the configuration, this helps a lot. The issue is that you have all of these samples in a single batch. bcbio then merges all of your samples into that batch so they can get processed together during the CNVkit calling step. At this point bcbio doesn't have the facilities to re-parallelize the processing out to other cores so will run everything on that machine.

We're currently working on an improved parallelization approach using CWL which can handle cases like this in a better way and could pre-parallelize the slow steps of CNVkit and then only do the merge and call in the final batch, but this is not really ready for use right now to help you here.

Practically it might be worth deciding if you need these to be called in a pool with CNVkit or can call them in a different way that helps avoid needing to batch them all together. If they do need to be pooled, you'll unfortunately need to wait for processing on a single machine.

Sorry to not have a better solution but hope this helps explain what is going on here.

**Comment by gabeng** [comment]
Brad,

what is the recommended configuration to process an entire run of samples (e. g. 96) with CNVkit? All samples are germline (there is no tumor/normal pairing). I remember reading somewhere that putting them in a batch in bcbio corresponds to building a reference from all samples. Is that correct?

Ben

**Comment by chapmanb** [comment]
Ben;
That's right, samples in a batch get a shared background so it's useful for those that share a common capture to get batched together. Hope this helps.

**Comment by gabeng** [comment]
Brad,
but then only one core is used. How can I use a shared background and still get parallel processing in bcbio?

**Comment by chapmanb** [comment]
Ben -- that is true, it will only use one machine for the batch, although will use multiple cores on that machine. Your best bet if you wanted to split the work across multiple machines right now is to group into batches of 8 or 12 or whatever processes in a reasonable time and then each of those batches would have a shared background but be independently parallelizable. Hope this provides a reasonable approach for now.

**Comment by gabeng** [comment]
Brad,
I am using a single machine on AWS and am experimenting how to size it according to the number of samples at hand. I see ```Resource requests: cnvkit; memory: 6.00; cores: 4``` in the debug log, but only one sample is processed at a time.
I know that you guys are probably more into WGS processing at a large scale and I am still dealing with smaller, medium-depth targeted panels. So our requirements may not exactly match.

A number of commands are used redundantly for every sample. Again, I have a large number of identical panels, so this prolongs processing time significantly.
* ```cnvkit.py access```: calculating accessible regions and GC content.
* ```cnvkit.py target``` and ```cnvkit.py antitarget``` are also only needed once, since all samples are sequenced with the same panel.

At this moment the overhead in bcbio is so large that I have to use cnvkit separately. 

An unrelated question: Why is ```--avg-size=50``` set for ```cnvkit.py target```? I am not looking at tumor deep-sequencing but rather cost-aware germline sequencing. My results with bcbio standard settings turn out to be rather noisy. 

Regards
Ben

**Comment by chapmanb** [comment]
Ben;
Thanks for the additional details and sorry about the poor performance right now. CNVkit is definitely not optimized for the single machine case and does do redundant work in the preparation. We want to improve and streamline this and will work on improving the parallelism and reducing the multiple runs. I'll take this on after the next release.

The `--avg-size` settings are meant for restricted panels (less than 1.0 of the genome) to provide additional resolution. Do you have restricted panels with lower relative depth? If so, it sounds like we need to add in some average depth checking here as well to avoid applying them under the wrong conditions.

Thanks again for the feedback and suggestions.

**Comment by gabeng** [comment]
Brad,
I am just scratching at the surface of CNVkit at this moment and my time box is over for now. Maybe we can contribute some code later on to optimize the integration. I really like your mantra that config settings should be standardized or automated (combined with good validation).  
Just some thoughts from my short journey with CNVkit:
* My panels tend to have a much lower read content off-target compared to the examples from Eric/CNVkit. I therefore have to make my antitarget bins orders of magnitute larger than bcbio standard settings. 
* The standard bin size on-target (approx 260bp) works much better for me than the 50bp in bcbio.

It would be great if bcbio could compute the optimum bin sizes at runtime. Ideally, these would be adaptive in CNVkit itself depending on the genomic region. In general, I am fighting with relatively high noise and variability in our ordinary data (germline cancer) so that I would tend to increase bin size.

Ben

**Comment by chapmanb** [comment]
Ben -- I pushed some fixes that should improve speed for single machine multicore runs by making full use of cores during coverage and segmentation. We're planning to have a new release soon with these fixes and then will tackle additional speed improvements and improving configuration settings for your capture panel cases.

My thought was to estimate depth and percent on/off-target and then use these as parameters for setting target/anti-target. I'll first calculate these as part of the preparation process and then once it's in place follow up with seeing what these report for your cases so we can define thresholds for setting them. Thanks again for helping with this.

**Comment by gabeng** [comment]
Brad, 
sounds great! I will report back how cpu utilization looks for me with these changes.
Also the depth estimate is a good idea. I will be happy to try this out on the various sample qualities that I have.

**Comment by etal** [comment]
Here's a script to quickly estimate reasonable average bin sizes from scratch: https://github.com/etal/cnvkit/blob/master/scripts/coverage_bin_size.py

If bcbio already has estimates of average on- and off-target depth for the cohort, then you can just divide 100000 by each of those values to get a sensible `--avg-size` argument value.

**Comment by gabeng** [comment]
Brad,
just some feedback on your latest changes: parallel processing with cnvkit now works much better. Thanks!

The next greatest improvement speedwise would be to remove redunant steps regarding `cnvkit.py access`, `cnvkit.py target` and `cnvkit.py antitarget`.

**Comment by chapmanb** [comment]
Eric -- brilliant, thanks for the great script to generalize this. I added support for that in the latest bcbio development, replacing the previous hard coding of sizes based on analysis type and percent coverage. Ben, I hope this will now do the right thing with your target regions in terms of choosing good bin sizes. I'd be happy to tweak further based on your testing.

Ben, glad the parallelization improves speed. Thanks for following up on that. I'll look at moving access calculation to an upstream process since it's not data specific. target/anti-target binning should be data dependent, especially with the new estimation of avg-size, so this makes the most sense to keep as is. Would eliminating redundancy in `cnvkit.py access` get you the run times you need? Thanks again for all the testing and feedback.

**Comment by roryk** [comment]
Thanks, looks like a bunch of these speed improvements made it in. Thanks so much everyone!
