### ISSUE TITLE
heterogeneity with exome data

### ISSUE THREAD

**Issue by ramaniak** [bcbio/bcbio-nextgen#1599]
Hello,
I am trying to understand if bcbio has (or is working on ) a pipeline for heterogeneity analysis from exome data? If so, would this still use Battenberg + Phylowgs? The docs mention battenberg with the following context : "files for Battenberg, which detects subclonality and copy number changes in whole genome cancer samples." I am therefore not sure how exome data would be handled for heterogeneity analysis.

Thanks very much
Arun

**Comment by chapmanb** [comment]
Arun;
Thanks for the question about heterogeneity analysis. We have a lot of experimental work in bcbio on running these analysis but nothing we feel is production ready, hence the lack of documentation. If you'd like to experiment, the path we have for heterogeneity calling in exomes uses CNVkit and BubbleTree (http://www.bioconductor.org/packages/release/bioc/html/BubbleTree.html):
```
variantcaller: [vardict]
svcaller: [cnvkit]
hetcaller: [bubbletree]
```
Battenberg (and thus PhyloWGS) require whole genome inputs so won't work with exomes. Ideally you'll also have matched normals for the somatic exomes. Hope this helps.

**Comment by chapmanb** [comment]
Arun;
We do have basic support for theta2 in bcbio but did not find it especially helpful in resolving heterogeneity for our test cases. It's a bit challenging to resolve how heterogeneity callers perform, due to lack of truth sets, but BubbleTree and Battenberg provided more uniform resolution on internal test cases where we had tumor/normal contamination estimates. Hope this helps.
