### ISSUE TITLE
RF: configuration template for joint genotyping and VQSR

### ISSUE THREAD

**Issue by joonan30** [bcbio/bcbio-nextgen#1681]
Hi Brad,

I am trying to do GATK joint-genotyping and VQSR only. Inputs are VCFs of multiple individuals generated by HaplotypeCaller, and provided from collaborators with pre-aligned bam files. Is there any template example for this? 

I could find one template for the no-align option but since I have VCF from HC, I'd like to specify the pipeline from combining VCFs to joint genotyping and VQSR.

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/templates/noalign-variant.yaml

Many thanks,

**Comment by chapmanb** [comment]
Joon;
Unfortunately we don't have an entry point in bcbio right now for only doing joint genotyping and VQSR starting with gVCFs. This is something we'd like to support so that we could do calling of new samples and inject previously called gVCFs into the procedure, but haven't yet had time to implement. Sorry to not have anything in place for you right now.

**Comment by roryk** [comment]
Thanks, we have a catch-all start-from gVCFs issue here, so closing in favor of that: #2336
