### ISSUE TITLE
Handle errors in case the initial queue submission (for the controller) fails

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#1814]
I'm not sure if this is bcbio specific or should go into ipython-cluster-helper instead. Basically, I had an invalid `slurm.conf` for my cluster and `sbatch` would error out if I tried to submit any job with memory specifications.

However, the pipeline went on and **still started** (rather, attempted to start) the cluster controller even if the initial batch submission failed. And of course it stayed there until timeout because no controller was started in the first place.

I didn't check if `sbatch` returns with an error code if this happens, but if it happens the pipeline should return an error and stop.

**Comment by roryk** [comment]
Hi Luca,

Thanks, sorry about that. I think this might be really hard for us to catch automatically. We submit the controller job and then the engine jobs, and we detect the engines coming up by seeing if they start sending messages to the controller. We don't actually watch the queue itself so we can't tell if the jobs are just pending or if there was a problem and the jobs never got submitted, we just know we're still waiting for them to come up. This is part of the reason that by default we set the timeout to be pretty low so that hopefully these kind of problems don't take hours to figure out. Sorry, I know that answer is really unsatisfying.

**Comment by lbeltrame** [comment]
Sorry, I didn't mean anything as complex as that. I mean that if `sbatch` returns with code !=0, abort, because that's what it was doing.

**Comment by roryk** [comment]
Thanks, closing this stale issue.
