### ISSUE TITLE
Installing genomes seems to require rtg which is missing.

### ISSUE THREAD

**Issue by drj11** [bcbio/bcbio-nextgen#1845]
I've installed bcbio without genomes, using `--nodata` (and this seems to work),
but when I try and install a genome I get:

`IOError: Could not prepare index rtg for GRCh37 by any method`

Evidently `https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz` is not found,
and in attempting to build an index using `rtg`, it doesn't find `rtg` either.

That's because I don't have `rtg` installed.

So... 
- does the documentation need to mention that I need `rtg`?
- should bcbio install `rtg` itself as a tool?
- should a pre-built version be available at `https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz`?

For completeness, will attach log in next comment.

**Comment by drj11** [comment]
Logs for the command `bcbio_nextgen.py upgrade --data --genomes GRCh37`

[upgrade_bcbio.sh.o463812.txt](https://github.com/chapmanb/bcbio-nextgen/files/824483/upgrade_bcbio.sh.o463812.txt)

**Comment by chapmanb** [comment]
David -- sorry about the issues. We do need to build the rtg indices locally but the failure is unexpected since bcbio does install rtg as part of the tools:

https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L95

It should get linked into the same path as `bcbio_nextgen.py`, which looks like `/usr/local/bin` here (is that right?), and then cloudbiolinux tries to add this path to the command.

Is it possible it got removed or paths got changed somehow? Does updated with `--tools` ensure it's installed and available for the data update/install? Hope this helps.
