### ISSUE TITLE
bowtie.py filter_multimappers

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#1864]
Hi @lpantano,
I have notice that the filter_multimappers function remove also all read coming from the ChrY/X  pseudoautosomal regions. (PARs). I was thinking that this maybe problematic.

what do you think?
Thanks!

The locations of the PARs within GRCh38 are:

PAR1: chrY:10,000-2,781,479 and chrX:10,000-2,781,479

PAR2: chrY:56,887,902-57,217,415 and chrX:155,701,382-156,030,895

PAR3: chrY:3,571,959-5,881,959 and chrX:89,145,000-92,745,001

**Comment by lpantano** [comment]
Hi


thanks for the comment.

What pipeline are you referring? chipseq?

You are saying that the multi mapper filter is removing reads from that but it shouldn’t? or it is doing that because they actually are multi mapping reads, because this region has high homology?

If that is, It is a difficult call, because I am sure this happens in other places, and not doing that will introduce a lot of more bias than recover real signal.

Do you have any experience in how to treat this cases? 

thanks

**Comment by apastore** [comment]
Hi, yes I have seen it in the chipseq pipeline where the filter_multimappers function is used. I guess is also happening for the other wenn the a reads falling in the 
Pseudoautosomal regions. 

Chr X and Chr Y have identical regions (Chr Y is most non coding except those regions). 

The hypothesis is that those gene code in those regions are so important that both male and female must have two copies. 

Some of those genes are involve in cancer an there are know mutation. 
http://www.nature.com/nature/journal/v516/n7530/fig_tab/nature13765_SF2.html

If we simply drop them by "multimapper" 
We are losing a lot of informations, in the Chip-seq pipeline but also in mutation calling and rnaseq. 


If I have understand correctly this post it look like the broad have remove the 
Pseudoautosomal regions form their genome reference. In this way they can call variant (and do other stuff there). Would be this an option for bcbio?
http://gatkforums.broadinstitute.org/gatk/discussion/1957/does-the-ug-call-variants-in-pseudoautosomal-regions-correctly

Thanks a lot!
Alessandro

**Comment by lpantano** [comment]
Hi

thanks for all the information. That function I think only affect chipseq, because mainly bowtie2 is only used for that pipeline as we recommend. 

If you create a genome without that regions, then that should work then. Nothing we need to do inside the code actually. 

Are you willing to create a genome with bcbio_setup_genemo.py and give it a try to see if that gives you regions there as well?

Meanwhile, I can think a little bit and see if we can remove multi-mapper except on those regions.

thanks!

**Comment by apastore** [comment]
Sure this is a good idea. I will do and let you know!

**Comment by chapmanb** [comment]
Alessandro and Lorena;
We use the Broad genomes with masked PAR regions so should be able to align uniquely to those places where it's possible with current approaches. If you think there are other regions that need masking for the work you're doing, using a custom genome as Lorena suggests is a good idea. We'd definitely welcome feedback if there are things we can improve, thanks for looking into this.

**Comment by apastore** [comment]
Thanks Brad, 
What are you saying it make sense the b37+decoy is masked on the ChrY PAR.

I am using the GRCh37 genome in bcbio for chipseq and I do not see any reads coming from those regions on both ChrX and ChrY. 

I will send a screenshot. 

Thanks for your help!

**Comment by roryk** [comment]
Thanks, closing for now since there hasn't been any action.
