### ISSUE TITLE
bcbio_system.yaml not in galaxy subfolder in Docker image

### ISSUE THREAD

**Issue by kmsteinberg** [bcbio/bcbio-nextgen#2091]
Hello,

I am using the latest Docker bcbio/bcbio. When I try to modify the bcbio_system.yaml file per the installation instructions, I get:

```cat: /usr/local/share/bcbio-nextgen/galaxy/bcbio_system.yaml: No such file or directory```

I looked in some other locations and it seems to be here:

```/usr/local/share/bcbio-nextgen/config/bcbio_system.yaml```

But when I try to run anything I get the following error:

```Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 36, in run_main
    config, config_file = config_utils.load_system_config(config_file, workdir)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 67, in load_system_config
    (config_file, os.path.join(base_dir, "galaxy")))
ValueError: Could not find input system configuration file bcbio_system.yaml, including inside standard directory /usr/local/share/bcbio-nextgen/galaxy```

I've tried this with the tags latest, v1.0.4, and v.1.0.2 and I get the same error.

Thanks,
KMS

**Comment by chapmanb** [comment]
Karyn;
Sorry about the issues. The Docker container is setup for running externally with bcbio_vm.py (https://github.com/chapmanb/bcbio-nextgen-vm) so that we can handle mounting the reference data and inputs into the container without having to do that yourself. The YAML is in a separate place since we merge the external bcbio_system.yaml where you set cores with the internal one. So it makes it a little bit tricky to run directly inside the container if you're mounting and setting everything up yourself.

Happy to give some advice about how best to do things as we're in a bit of a transition period with Docker moving to use CWL runners (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html) and automated builds that work with them (https://github.com/bcbio/bcbio_docker). Sorry that the Docker experience is not totally clean right now as we move over. If you let us know how you're trying to run things hopefully I can provide more helpful specific advice. Thanks again for the report.

**Comment by kmsteinberg** [comment]
Thanks, Brad. I am cc'ing Jason Walker because I think he is interested in learning more about your CWL workflows.

KMS


> On Oct 4, 2017, at 3:27 PM, Brad Chapman <notifications@github.com> wrote:
>
> Karyn;
> Sorry about the issues. The Docker container is setup for running externally with bcbio_vm.py (https://github.com/chapmanb/bcbio-nextgen-vm) so that we can handle mounting the reference data and inputs into the container without having to do that yourself. The YAML is in a separate place since we merge the external bcbio_system.yaml where you set cores with the internal one. So it makes it a little bit tricky to run directly inside the container if you're mounting and setting everything up yourself.
>
> Happy to give some advice about how best to do things as we're in a bit of a transition period with Docker moving to use CWL runners (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html) and automated builds that work with them (https://github.com/bcbio/bcbio_docker). Sorry that the Docker experience is not totally clean right now as we move over. If you let us know how you're trying to run things hopefully I can provide more helpful specific advice. Thanks again for the report.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>



Karyn Meltz Steinberg, Ph.D.
McDonnell Genome Institute
Washington University School of Medicine
4444 Forest Park Blvd
St. Louis, MO 63108
office/314.747.9015
mobile/404.547.0818
kmeltzst@wustl.edu



________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by jasonwalker80** [comment]
Karyn was intending to run bcbio once to evaluate the SV workflow. I was hoping we could get the SV workflow in CWL format this way. Then we could tweak it if needed and incorporate into our infrastructure. 

If we could get a version of the SV workflow as CWL that would be great.

As for the running environment Karyn is using, we have a LSF scheduled compute cluster that now requires a docker image name to submit jobs. The network filesystem is mounted by a wrapper around docker but direct interaction with docker is not allowed. Since we are unable to have root access on the hosts, all ports are closed.

Local compute and installing software on the network filesystem is not something that's supported at our institution. It can still be done, but it's left as an exercise to the user. For running a single workflow, would you advise installing on a local filesystem at this point instead of attempting the docker image or VM?

**Comment by chapmanb** [comment]
Jason and Karyn;
Thanks much for the additional details. Practically, is a local non-Docker based install out of the question for right now? Is your system docker only? If you just want to run SV calling a local install would be the most well supported and straightforward path on LSF.

We do have very early support for sv calling with CWL that would run using Toil (https://github.com/BD2KGenomics/toil) but we are still working on scaling and making that easy to debug so it might be frustrating to try to get going.

Happy to help support whichever way works for you but just don't want to leave you frustrated with early stage work on our side.

**Comment by jasonwalker80** [comment]
Thanks @chapmanb! A local install is still technically possible at a small scale. The timeline for this hardware is limited but it's still an option for testing the SV workflow.

Toil is currently the workflow manager we've been using with CWL, Docker and LSF as the scheduler. The alternative to writing our own SV workflow in CWL from scratch is finding one that is available as a starting point. If you have even a buggy version that still needs work, it's probably a better starting point than writing one from scratch. 

Also, Karyn's requirements for SV callers is nearly identical to what you've implemented in bcbio.

**Comment by chapmanb** [comment]
Jason;
Thanks for all the details. Trying out a local install of bcbio is definitely the best path forward for running right now. Glad it's an option and let me know if I can help with any issues at all. I'm really glad we've implemented a useful set of callers, and we're always looking to better validate and improve them so happy you're looking at them.

I'll definitely ping as well when Toil + CWL is ready for your SV calling testing as. We're working on it currently and hopefully will have something for you soon. Thanks again for volunteering to help and test with this and hope the local install gets you useful data in the short term.

**Comment by roryk** [comment]
Questions were answer
