### ISSUE TITLE
Picard metrics in multiqc

### ISSUE THREAD

**Issue by schelhorn** [bcbio/bcbio-nextgen#2113]
This doesn't have too high a priority, but I was wondering why the Picard metrics that [appearently can be generated in bcbio](https://github.com/chapmanb/bcbio-nextgen/blob/5defac5c7b46db4be87a0a2d90558029e8e96f1c/bcbio/broad/metrics.py) do not seem to appear in my `multiqc` reports [(although the latter has modules for processing these metrics)](https://github.com/ewels/MultiQC/tree/master/multiqc/modules/picard). I'm especially interested in the following Picard readouts:

- CollectRnaSeqMetrics: _RnaSeqMetrics_
- CollectAlignmentSummaryMetrics: _AlignmentSummaryMetrics_
- CollectHsMetrics: _HsMetrics_
- CollectTargetedPcrMetrics: _TargetedPcrMetrics_ 
- CollectWgsMetrics: _WgsMetrics_
- CollectVariantCallingMetrics: _VariantCallingDetailMetrics_ and _VariantCallingSummaryMetrics_
- SequencingArtifactMetrics
- CollectOxoGMetrics
- ErrorSummaryMetrics

Is there a _bcbio_ configuration setting that is required to enable the generation of these metrics and their subsequent inclusion in `multiqc`?

**Comment by chapmanb** [comment]
Sven-Eric;
We'd mostly removed and replaced Picard metrics due to speed issues running them. They were mostly single core and required iterating over the entire BAM file multiple times so took excessive amounts of time with WGS runs. I know there has been a lot of work on Picard recently so this might have improved. Are there specific metrics you're missing from other methods that you'd like to have? We could definitely consider adding things back in but want to avoid having a lot of duplicated metrics to maintain and present in MultiQC. Thanks for starting this discussion.

**Comment by schelhorn** [comment]
I see; the runtime may still be an issue, I don't know. We are using Picard QC for the clinical pipeline and so I was interested in having it available preclinically in our bcbio setup as well. `multiqc` already supports reading the Picard outputs and so maintenance would be dealt with the, but of course scalability matters. 

Concerning metrics I am most interested in the last three collections in my list as well as in the strand bias metric from the alignment connection; all these can be used to diagnose the quality of FFPE samples (or frequent lack thereof), which are of high clinical importance (as I'm sure you am aware). Here the [gist of it](http://genomics.broadinstitute.org/data-sheets/error-proofing-exome-sequencing-somatic-variant.pdf) from an Illumina poster.

**Comment by schelhorn** [comment]
@mjafin, do you have any interests/insights concerning FFPE QC in bcbio that you may want to share here?

**Comment by mjafin** [comment]
Hi @schelhorn 
For FFPE we usually look at the rates of C>T (G>A) variants and generally the alignment rates. On top of that, the `damage_filter` summary in MultiQC is very useful for spotting the most degraded samples. I just ran a batch of ~90 samples where there were cell lines, FFPE-ised cell lines and real clinical samples (commercial FFPE) and you can tell which ones are the FFPE samples.

**Comment by schelhorn** [comment]
Hmm, interesting - thanks Miika. We spoke at length with the DKFZ bioinformatics core (which is located near to us), and they aren't using their own damage filter for FFPE samples since they say it doesn't help much. Instead, for FFPE they are looking at measures that can be generated by Picard's SequencingArtifactMetrics/CollectOxoGMetrics/ErrorSummaryMetrics. Alignment rates help a little, but FFPE-damaged samples may contain reads that align just fine but still cannot be used for variant calling due to increased rates of specific nucleotide exchanges - only some of which are C>T, I believe.

**Comment by ohofmann** [comment]
Our own experience with https://github.com/eilslabs/DKFZBiasFilter has been mixed -- at least for our standard FFPE samples it doesn't seem to find a whole lot of bias. How are you using the se three Picard metrics to identify sample issues?

In terms of runtime it's really tough to justify for our WGS runs; I don't suppose GATK4 will do anything to change that?

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for discussing with the DKFZ folks. It's not great they don't find their own tool that useful. As Oliver said, it does help in some cases but not all. It does detect any sort of bias so can pick up things generally. The major advantage over the Picard metrics programs is that it annotates calls so you can flag potentially problematic reads. In my mind it's not as useful to say "This sample has FFPE damage" because people generally knew that was a possibility coming in and want to be able to extract whatever useful data they can.

So that's why I preferred this solution over the picard metrics initially. I'm not sure of other good alternatives that do per-variant flagging. GATK4 has OxoGReadCounts (https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_gatk_tools_walkers_cancer_OxoGReadCounts.php) but that is a MuTect2 only annotation.

Do you know of downstream approaches from the Picard metrics that would help with this? How were you planing on using the information from those? Thanks much for the help thinking through alternative ways to detect and improve damage assessment here.

**Comment by roryk** [comment]
Thanks, closing as there hasn't been much action on this and it seems like the consensus is that what is in there is reasonable.
