### ISSUE TITLE
promoting tool citation

### ISSUE THREAD

**Issue by brentp** [bcbio/bcbio-nextgen#2125]
I wonder if there's a way that bcbio can promote citing the tools used in an analysis. I think it's easy to omit a tool like peddy that a project will (hopefully) use (hopefully) once, and then move on. I know I am guilty of omissions of this sort. Since, to some degree, citations are the currency that keep me (and a lot of us) employed, it would be nice to facilitate that in bcbio. e.g. in a pipeline that uses GATK, samtools, indexcov, multiqc, picard, bcbio could output a citation file with dois and citations in some format. Likewise if it annotates with VEP, ensembl or gnomad

I put this issue here not because bcbio is an offender, but because it's a centralized place to facilitate this. Thoughts?

**Comment by schelhorn** [comment]
For what it's worth, I agree. Make looking up the author and benchmarking data user in the publication easier as well. Could also contain they link to the repo, if available. Had to be maintained by someone, though ;)

**Comment by chapmanb** [comment]
Brent and Sven-Eric;
Thanks for starting this discussion, it would be great to make it easier for folks using bcbio to give academic credit for code and tools used in workflows.

From a representation side, I'd propose including the citation information as part of bioconda packages. There is in progress work to provide links to biotools (https://github.com/bioconda/bioconda-recipes/pull/6294) which we could then use to query publications (https://bio.tools/bedtools) and try to generate an output report from a bcbio run. This could expand the version file we currently provide with richer metadata. This way we're not maintaining these in bcbio but as part of a larger project.

Data is harder because our installs are not as structured. We're using ggd recipes which have unstructured comments in the headers for provenance. I've still been waiting to support a bioconda-like data project if anyone gets one started.

Definitely happy to hear other approaches. Thanks again for the discussion.

**Comment by schelhorn** [comment]
Don't know if it's maintained, but I recall the [SciCrunch DB](https://www.nature.com/news/researchers-argue-for-standard-format-to-cite-lab-resources-1.17652) in that context.

**Comment by lbeltrame** [comment]
> which we could then use to query publications (https://bio.tools/bedtools) and try to generate an output report from a bcbio run. 

That would be extremely useful. When writing methods for papers it is not unusual that I miss one citation or two given the plethora of tools that are used.

**Comment by naumenko-sa** [comment]
The citation list is updated as a first approximation. Everybody is welcome to contribute and make it better!
- https://bcbio-nextgen.readthedocs.io/en/latest/contents/citations.html
- https://github.com/bcbio/bcbio-nextgen/blob/master/docs/contents/citations.md
