### ISSUE TITLE
Improve job reuse for CWL on Arvados

### ISSUE THREAD

**Issue by tfmorris** [bcbio/bcbio-nextgen#2212]
I ran a bcbio-generated Sentieon-based pipeline with 6 samples on Arvados and had one of the samples fail during the alignment step, so removed it, regenerated the workflow and resubmitted it.

I was hoping that it would reuse the successful jobs for the 5 non-failing samples, but instead it restarted everything from scratch, including the fairly expensive alignment.

I'll try and investigate this a little bit more to narrow down the cause, but one thing that caught my eye was the diffs in the generated CWL (attached). It seems like sample/run specific parameters (in this case `outdirMin`, `tmpdirMin`, `indirMin`) could be moved out of the CWL to a YAML file.
 
[bcbio-generated-cwl-diffs.txt](https://github.com/chapmanb/bcbio-nextgen/files/1616303/bcbio-generated-cwl-diffs.txt)

**Comment by chapmanb** [comment]
Tom -- thanks for looking at the differences preventing re-use here. bcbio does try to keep the CWL as stable as possible to enable re-use but in this case changing the disk requests makes sense because we've changed the samples being processed in different locations. This directly translates into instance types so I believe is the right place to specify it.

I'd argue that Arvados should ignore disk/CPU/memory requirements when calculating re-use. In some strict sense having different instance types might break reproducibility if outcomes were somehow tied to the machine type but in practice you should be able to tune up/down cores and disk and re-use previously finished steps. Would it be possible to ignore these when calculating re-use?

**Comment by tfmorris** [comment]
Good point about ignoring resource requirements when deciding whether steps are equivalent -- and Arvados already does that.

In looking a little closer, I suspect the culprit is the vendor private extension dx:InputResourceRequirement. Because it's non-standard, there's no way for a CWL processor to tell whether changes in it can be safely ignored. I'll see if I can confirm my guess.

**Comment by roryk** [comment]
Thanks, closing for now as we're not doing a ton of development in this area, and this is stale. Please re-open if there is something specific we can improve. Thank you!
