### ISSUE TITLE
TPM file is not generated in RNASeq processing

### ISSUE THREAD

**Issue by manasa-surakala** [bcbio/bcbio-nextgen#2235]
Hi, 
The overall TPM file gene.sf.tpm.tsv is not being generated for RNASeq processing (Bcbio 1.0.4 version). I am using tximport every time I process new data. Can this be included in post-processing soon? Thanks for you help!
Regards,
Manasa

**Comment by roryk** [comment]
Hi Manasa,

We've dropped that file since the appropriate way to get the gene level TPM values is by using tximport and turning on the length scaling. We're working on getting Alexandra's nice MultiQC integration into bcbioRnaseq so we can generate all of this stuff automatically. I'll update this issue when we've got that working.

**Comment by roryk** [comment]
Oop, didn't mean to close this one.

**Comment by manasa-surakala** [comment]
Hi,

Tximport is giving TPMs at gene level. How do we generate isoform TPMs? I checked if we need to tweak a bit with tximport command but that doesn’t seem to work. Please let me know.

Thanks,
Manasa

**Comment by roryk** [comment]
Hi Manasa,

https://bioconductor.org/packages/3.7/bioc/vignettes/tximport/inst/doc/tximport.html has some information about how to do that, if you do:

`txi.tx <- tximport(files, type = "salmon", txOut = TRUE)`

you will get the transcript level calls instead of the calls collapsed down to the gene level.

**Comment by roryk** [comment]
We generate TPM files now with bcbioRNASeq, so this should be all set.
