### ISSUE TITLE
Multiple BAM files written with Parallel execution

### ISSUE THREAD

**Issue by skandlab** [bcbio/bcbio-nextgen#2240]
Hi Brad et al.,

I am using bcbio v1.0.3. I recently started an ipython parallel run with a very large T/N normal pair (~800Gb fastq.gz). I have been experiencing many I/O problems/errors with this run (smaller ~200Gb files run fine, we have been running hundreds of these). I just checked the temporary directory and saw multiple bam files being written in parallel during the 'ipython: delayed_bam_merge' step; is this intended?

/tmp/skandera/tmp/tmpvatZfS:
total 61G
-rw------- 1 skandera gis   61G Jan 27 10:37 mysample-T-sort-prep.bam
-rw------- 1 skandera gis 1002K Jan 27 10:36 mysample-T-sort-prep.bam.bai
-rw------- 1 skandera gis   36K Jan 27 10:16 mysample-T-sort-prep.list

/tmp/skandera/tmp/tmpPXoMEU:
total 684G
-rw------- 1 skandera gis 684G Jan 27 10:37 mysample-T-sort-prep.bam
-rw------- 1 skandera gis  11M Jan 27 10:34 mysample-T-sort-prep.bam.bai
-rw------- 1 skandera gis  36K Jan 27 06:50 mysample-T-sort-prep.list

/tmp/skandera/tmp/tmpJNlB1V:
total 693G
-rw------- 1 skandera gis  12M Jan 27 10:37 mysample-N-sort-prep.bam.bai
-rw------- 1 skandera gis 693G Jan 27 10:37 mysample-N-sort-prep.bam
-rw------- 1 skandera gis  36K Jan 27 06:50 mysample-N-sort-prep.list

/tmp/skandera/tmp/tmp65bKwS:
total 695G
-rw------- 1 skandera gis 695G Jan 27 10:37 mysample-N-sort-prep.bam
-rw------- 1 skandera gis  12M Jan 27 10:36 mysample-N-sort-prep.bam.bai
-rw------- 1 skandera gis  36K Jan 27 06:50 mysample-N-sort-prep.list

/tmp/skandera/tmp/tmpSytM0X:
total 691G
-rw------- 1 skandera gis 691G Jan 27 10:37 mysample-T-sort-prep.bam
-rw------- 1 skandera gis  11M Jan 27 10:32 mysample-T-sort-prep.bam.bai
-rw------- 1 skandera gis  36K Jan 27 06:50 mysample-T-sort-prep.list

/tmp/skandera/tmp/tmpS_kjG0:
total 690G
-rw------- 1 skandera gis 690G Jan 27 10:37 mysample-T-sort-prep.bam
-rw------- 1 skandera gis  11M Jan 27 10:33 mysample-T-sort-prep.bam.bai
-rw------- 1 skandera gis  36K Jan 27 06:50 mysample-T-sort-prep.list

/tmp/skandera/tmp/tmpQIgMeW:
total 699G
-rw------- 1 skandera gis 699G Jan 27 10:37 mysample-N-sort-prep.bam
-rw------- 1 skandera gis  12M Jan 27 10:35 mysample-N-sort-prep.bam.bai
-rw------- 1 skandera gis  36K Jan 27 06:50 mysample-N-sort-prep.list

/tmp/skandera/tmp/tmpZVRW08:
total 699G
-rw------- 1 skandera gis 699G Jan 27 10:37 mysample-N-sort-prep.bam
-rw------- 1 skandera gis  12M Jan 27 10:35 mysample-N-sort-prep.bam.bai
-rw------- 1 skandera gis  36K Jan 27 06:50 mysample-N-sort-prep.list

**Comment by chapmanb** [comment]
Anders;
Thank you for the report and apologies about the issues. We've significantly re-worked how the post-alignment recalibration/realignment process works since the 1.0.3 release so this could signal an issue with how it had been done in the past. At this point, I'd have a couple of practical suggestions:

- Do you need recalibration and realignment? These are typically not necessary with realignment based callers and avoiding these steps would save a lot of processing and IO time for large BAM files like these.

- Are you in a position to update to a more recent bcbio version? We're hoping to have a 1.0.8 release this week which incorporates GATK 4.0 support and should be much more effective for doing recalibration if you'd still prefer to include that in your analysis.

Sorry to not have a definite fix but hope one of these two options will work to improve your analysis runtimes.

**Comment by skandlab** [comment]
Sounds good, we will try 1.0.8 and GATK4. Just wanted to report this.

Thanks for all the amazing work!
