### ISSUE TITLE
dbGAP dowload

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2259]
Hi I have to download a large amount of file from a restricted access dbGAP. I was wondering if this could be done directly from bcbio prepare sample using the dbGAP project private key (configured in vba-config). 

Alternative would be possible to let bcbio convert the SRA files to fastq using the standard bcbio_sample.csv?

Tranks a lot 
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Unfortunately we don't have direct support for dbGAP access or SRA conversion as part of bcbio. We generally prefer to have this type of work be upstream of bcbio rather than integrated. If you end up writing a program to do this and prepare fastqs we'd be happy to include a link to it from the documentation.

**Comment by roryk** [comment]
Thanks for the suggestion, and agree with Brad's assessment. Better to do this kind of stuff upstream.
