### ISSUE TITLE
Pipeline standardization

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2260]
Hi Brad,

I'm sure you've already seen [this blogpost](https://gatkforums.broadinstitute.org/gatk/discussion/11398/batch-effects-begone-introducing-the-functional-equivalence-data-processing-pipeline-spec) on the GATK forum, and the associated [guidelines](https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md).

I'd like to know what your take is on this subject, and if you're planning to follow these guidelines once they're accepted. Does something like this fit into your vision for bcbio? From our side, it'd be a huge help to be able to reference to guidelines for the standard pipeline.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Thanks so much for starting this discussion. This is awesome work and I'm excited to make bcbio pipelines compatible with what they do (with the option of adjusting as it makes sense, as we do right now). I left a detailed note on the post with some thoughts and discussion items:

https://gatkforums.broadinstitute.org/gatk/discussion/comment/45965/#Comment_45965

I'll start to work immediately on bringing BQSR in line with their suggestions: downsampling to save time and binning to save disk space make good sense. Then I'd like to evaluate the proposed changes and adjust to those provided they don't disrupt current workflows. It would be great to hear any other thoughts about the standardizations and potential adjustments. Thanks again for the discussion.

**Comment by matthdsm** [comment]
Hi Brad,

I'm glad we're on the same page on this. As is said in the blogpost, we're probably going to have to wait for the paper to get to the nitty gritty, but in the mean time, I'd like to propose the following:

If the set standard diverges too much from what you have right now in the `variant2` analysis, would it make sense to add a whole new 'pipeline' which adheres strictly to the standard? If they do decide to be rigid and stick with tools like picard over biobambam, this might implicate a performance hit, but it might be useful for people looking to stick to the standard as close as possible.

Cheers
M

**Comment by schelhorn** [comment]
The (open) question to me is whether it makes sense for bcbio to adhere to a standard that is not well justified (by the data). 

Bcbio is great because it tries to make the most accurate and scalable pipeline, which requires constant validation and innovation. If the GATK people really are going for a strict implementation then that's dead in the water anyway, in my opinion. 

They are better advised to define good KPIs and reference data and let everyone compete fulfilling these benchmarks with their own pipelines (i.e., functional equivalence). They could still offer a CWL or WDL of their implementation as a reference to improve on, of course.

That's just one opinion, obviously.

**Comment by chapmanb** [comment]
Matthias and Sven-Eric;
Thanks for these thoughts. The goal of bcbio here is to be compatible where it makes sense with validations for SNPs, Indels and SVs. We'll try to do this in the least divergent manner possible; maintaining multiple independent pipelines is a lot of work and we try to build things in bcbio that we can reasonably support over time. I'm going to tackle the BQSR recommendations first since that seems a definite improvement in terms of runtimes and disk usage, and then will look at the bwa-mem and duplication changes after we have some test data to work from. We can then decide the best way to proceed -- either stick with current approaches since they are equivalent in validations or adjust with configurability trying to keep as much as possible the same. It would be great to hear thoughts from other folks as well, always happy to hear opinions and suggestions.

**Comment by schelhorn** [comment]
Refering to https://www.biorxiv.org/content/early/2018/02/22/269316

**Comment by chapmanb** [comment]
Apologies, closed incorrectly with wrong issue number.
