### ISSUE TITLE
Feature request: integrate vcf2maf

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#2293]
Hi there,

what is your opinion on integrating a vcf2maf tool such as [this tool from MSKCC](https://github.com/mskcc/vcf2maf) ?

I think in regard to many downstream applications that nowadays use maf tools as an input it would be a compelling option to include...

Curious what you think,
leiendeckerlu

**Comment by chapmanb** [comment]
Thanks for the suggestion and starting this discussion. In general, we're happy to make it easier to produce other standard file formats if they're useful. It sounds like this tool would be most useful integrated with the VEP portion of the pipeline since it uses it as input:

https://github.com/chapmanb/bcbio-nextgen/blob/8e2859ed80d501008e27fab493bf0f1871e922d5/bcbio/variation/effects.py#L118

The tool itself is present in bioconda, but looks like it might need some tweaking to not double call VEPand work directly from the output of bcbio.

It sounds like the first step would be to understand what it takes to convert the bcbio VEP VCF into a useful maf output, and then determine how that could fit into bcbio.

Hope this helps as a starting point and happy to help as you explore this. Thanks again.

**Comment by leiendeckerlu** [comment]
Thanks for the very valuable background information how vcf2maf might work best with bcbio.

I will look into this and keep you posted on my progress.

**Comment by lbeltrame** [comment]
I wrote some rough Python code which does the same conversions as vcf2maf without having to run it. 

Some of the bits are tricky because frameshifts for example need to be called `Frame_Shift_Ins` or `Frame_Shift_Del` depending on whether there is an insertion or a deletion. I also put the various conversions in a YAML file for easier changes (in case someone finds it useful: https://gist.github.com/lbeltrame/27c21e4879e78f88ac568f3d10354836 - licensed under CC0; note `Frame_Shift_` due to the reasons above). 

I did this mainly because I don't well understand the code in `vcf2maf` (I was and am still not very good at Perl).
