### ISSUE TITLE
No VEP effect TSV/CSV output file in /final/ folder in 1.0.8 ?

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#2298]
Hi there,

I was wondering if the VEP output table (CSV/TSV) that in previous versions was part of the /final/ output is no longer being provided? I can very well find the vcf files that have been annotated with VEP but I always found this additional CSV/TSV output file very convenient to sort for and look at particular types of variants.
I also did not find this file in any of the intermediate directories.

I'm using bcbio 1.0.8.

Thank you.

**Comment by chapmanb** [comment]
Thanks for checking about this. I'm not 100% sure about the change in the file format as we're not big users of VEP but I believe this change might have happened as a result of switching over to the new faster `vep` script: https://github.com/Ensembl/ensembl-vep#vepdiffs 

@matthdsm -- do you happen to know this history of this file in detail?

What outputs were useful from this file? It looks like the new VEP can generate a textual stats file (gguseast.ensembl.org/info/docs/tools/vep/script/vep_options.html#basic) but not sure if that has the useful information you needed.

In general we've tried to move to supplying more single VCF files that get annotated and parsed downstream since we now can also annotate with vcfanno, as this tries to make the outputs a bit more consistent. Are there things in the previous version of the files that are missing from the VCF, or were those just easier to parse?

Thanks again for the discussion.

**Comment by leiendeckerlu** [comment]
To be more precise about the file that I'm missing (and of which I think that it was part of the output in previous bcbio versions)
http://www.ensembl.org/info/docs/tools/vep/vep_formats.html entitles the file that I'm looking for as "Tab-delimited output" which can be retrieved by running vep with the "--tab" flag:

> Tab-delimited output
> The --tab flag instructs VEP to write output as a tab-delimited table. This differs from the default output format in that each individual field from the "Extra" field is written to a separate tab-delimited column. This makes the output more suitable for import into spreadsheet programs such as Excel. This is also the format used when selecting the "TXT" option on the VEP web interface.

And what I'm now basically missing is this tab-delimited output file for all the VCF files that are in the /final/ folder, e.g. the ensemble callsets but also the individual VCF caller files...

To put it into pseudo-code:

`./vep --cache -i ensemble.vcf --tab -o ensemble.txt `

Thank you.

**Comment by matthdsm** [comment]
Hi,

I'm also unsure what file you are talking about. The flag you provide forces vep to output the variants and annotations in a tab delimited format. However, this disables the vcf formatted output, and thus would break all downstream steps in bcbio. If you want your vcf in a tab delimited format, I suppose there are lots of tools which can provide that functionality.

Cheers
M

**Comment by pfpjs** [comment]
Hi,

To "convert" the VCF to a tab-delimited file suitable for downstream analysis, I just dump the gemini database:

``gemini query --header -q "select * from variants" <gemini.db> > gemini-db.csv``

Would this work for your purposes?

**Comment by matthdsm** [comment]
You could also use the GATK.

https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_variantutils_VariantsToTable.php

M

Op 5 mrt. 2018 om 15:13 heeft Paulo Silva <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi,

To "convert" the VCF to a tab-delimited file suitable for downstream analysis, I just dump the gemini database:

gemini query --header -q "select * from variants" <gemini.db> > gemini-db.csv

Would this work for your purposes?

**Comment by roryk** [comment]
Thanks, this is super old so closing it out.
