### ISSUE TITLE
Bamcoverage and ATAC-seq 

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2302]
Hi @lpantano,
I have seen that you are adding support for deeptools bamcoverage, thanks a lot for this, really nice. I was just wondering if these two parameter 
--extendReads 150 --centerReads  could be not set as default, since I guess They maybe problematic with the ATAc-seq pipeline ? 

Thanks a lot !

**Comment by lpantano** [comment]
Hi,

You are right and we are checking with some data the effect. Hopefully we can find the best values in a week or so.

Thanks!

**Comment by lpantano** [comment]
Hi,

sorry for the delay. @mistrm82 looked into some of our data and it looks fine with those parameters. If you have better ones and you can test it, i am happy to have separate values for each pipeline.

cheers

**Comment by crazyhottommy** [comment]
googled for something else and found this. want to chime in. 
for ATACseq, people may only want to pile up the Tn5 cut sites, if it is paired-end reads. only the 5' sites of each read are used, so --extendReads 150  may not be ideal.

ATACseq also gets read signal from mon- and di-nucleosomes in addition to the open chromatin regions.  from the help page of bamCoverage

```
--minFragmentLength INT
                        The minimum fragment length needed for read/pair
                        inclusion. This option is primarily useful in ATACseq
                        experiments, for filtering mono- or di-nucleosome
                        fragments. (default: 0)
```
Although I am bit confused, is not `--maxFragmentLength 147` should be used instead of --min?
