### ISSUE TITLE
Fail upgrade due to some 404 at sourceforge

### ISSUE THREAD

**Issue by drj11** [bcbio/bcbio-nextgen#2314]
I'm running

   /usr/local/extras/bcbio-nextgen/2017-08/tool/bin/bcbio_nextgen.py upgrade --tools --data --genomes hg38 --genomes GRCh37 --aligners star --aligners bwa --aligners bowtie2

on our cluster at Sheffield.
I have write access to `/usr/local/extras/bcbio-nextgen/2017-08`.

Currently (I've ran it a couple of times) it stopser about 8 minutes with:

    subprocess.CalledProcessError: Command '['wget', '-c', '-O', 'snpEff_v4_3_1_GRCh37.75.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v4_3_1/snpEff_v4_3_1_GRCh37.75.zip']' returned non-zero exit status 8

Full log here: https://gist.github.com/drj11/d6ed6542bf079f6579e2a2d01ffd4552

Anything I can do about this?

**Comment by chapmanb** [comment]
David -- thanks much for the report and sorry about the issue. This is a due to sub-versioning within snpEff as we've tried to move to the latest version (we need to fetch 4.3, not 4.3.1 files). There is a fix in place in development but this makes me realize the whole process is broken for the previous release which we don't want. I pushed a fix to revert to the older version until the next release. So if you remove any cached cloudbiolinux downloads (`rm -rf tmpbcbio-install`) and re-run the same command it should now work cleanly. Thanks again for the detailed report.
