### ISSUE TITLE
Running CNVkit from ready-bam files

### ISSUE THREAD

**Issue by sxv** [bcbio/bcbio-nextgen#2316]
Hi,

I often run paired tumor/normal samples from FASTQ through bcbio to get SNV and CNV calls.

My question is: if I want to re-run the cnvkit analysis on a case that has already run, can I start from the *-ready.bam files that are produced by bcbio?

And if so, can I remove the following config parameters (i.e. have they already been completed upstream from the *-ready.bam files)?
      aligner: bwa
      mark_duplicates: true
      recalibrate: true
      realign: true

I am doing this and I get an error message: I need to add "bam_clean: fixrg". I have done this and the case is now running, but I want to make sure that this modified approach will produce equivalent cnvkit results as if I have started from FASTQ.

Thanks,
Sujay

**Comment by chapmanb** [comment]
Sujay;
Thanks for the question. You can use the pre-aligned BAMs as inputs to only CNVkit without any issues. As you already figured out, you'd just want to set `aligner: false` and remove any other post-processing steps. bcbio requires that the sample name in the BAM matches that specified in the `description` field, so you can either match these, or specify `bam_clean: fixrg` to have it manually fix it.

Otherwise all will run as if doing the alignment in the same process. Hope this helps and please feel free to reopen if you run into any issues.
