### ISSUE TITLE
Kallisto fails while trying to build index

### ISSUE THREAD

**Issue by ivirshup** [bcbio/bcbio-nextgen#2323]
I've got a `bcbio` installation made with:

```
python bcbio_nextgen_install.py "$PWD/bcbio" --tooldir="$PWD/bcbio_tools" --genomes hg38-noalt --isolate
```

I'm trying to add a genome build with ERCCs included with the command:

```
bcbio_tools/bin/bcbio_setup_genome.py \
  --fasta bcbio/genomes/Hsapiens/hg38-noalt/seq/hg38-noalt.fa \
  --gtf bcbio/genomes/Hsapiens/hg38-noalt/rnaseq/ref-transcripts.gtf \
  --name Hsapiens \
  --build hg38-noalt-ercc \
  --ercc
```

Which ends in the following error:

```
kallisto: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory
```

Any tips for fixing this? Thanks!

**Comment by chapmanb** [comment]
Isaac;
Sorry about the issue and thanks for the report. This looks like it's due to not having the latest kallisto install which compiles against the most recent hdf5 library (which changed version numbers). If you manually upgrade kallisto:
```
bcbio_conda update -c bioconda kallisto
```
This should hopefully fix the issues. Please feel free to reopen if this doesn't fix it and you run into other problems.

**Comment by ivirshup** [comment]
Looks like that worked, thanks!

If I make a fresh install, should I expect to need to run that command again?

**Comment by chapmanb** [comment]
Thanks for reporting back and glad to hear it worked. We're pinning kallisto to the latest version during the install so it should hopefully run cleanly on any new installs/upgrades. If you keep seeing reversions please let us know and we can try to figure out what package dependencies cause the issues. Thanks again.
