### ISSUE TITLE
peddy fails

### ISSUE THREAD

**Issue by miccec** [bcbio/bcbio-nextgen#2384]
Hello,
I am running bcbio for somatic variant calling on WES tumor/normal.
The step of peddy runs forever and does not stop. is there a way to disable this step?
Thank you
Michele

**Comment by chapmanb** [comment]
Michele;
Thanks for the report and apologies about the issue. We haven't seen incredibly long runtimes with peddy and would like to sort out what is happening problematic with your sample so we could fix. Would you be able to share the end of your `log/bcbio-nextgen-debug.log` file so we can see what peddy is doing? If you can debug in real time it would also be useful to confirm that peddy is running by looking at `top` and also examine the `run-stderr.log` file that you can see the location of by looking at the peddy command in `log/bcbio-nextgen-commands.log`. If you could share these via a gist (https://gist.github.com/) that might give us more idea of what is happening and how to fix. Thanks for the help debugging.

**Comment by miccec** [comment]
Hi, thanks for your reply. 
The peddy command is running forever. With the command "ps -ef | grep peddy" I  see 39 peddy processes.
The last command in the log/bcbio-nextgen-commands.log is: 
/storage/gluster/vol1/bcbio/anaconda/bin/peddy -p 39 --plot --prefix /storage/gluster/vol1/SHARED/HOMEFOLDERS/ceccarelli/LAURAPAPI/bcbiotx/tmpRJ5qL3/patientID-16 /storage/gluster/vol1/SHARED/HOMEFOLDERS/ceccarelli/LAURAPAPI/ensemble/patientID-16/patientID-16-ensemble-effects.vcf.gz /storage/gluster/vol1/SHARED/HOMEFOLDERS/ceccarelli/LAURAPAPI/ensemble/patientID-16/patientID-16-ensemble-effects.ped 2> /storage/gluster/vol1/SHARED/HOMEFOLDERS/ceccarelli/LAURAPAPI/bcbiotx/tmpRJ5qL3/run-stderr.log

And you can find the run-stderr.log here:  
https://gist.github.com/miccec/441bdd310eccb446a5f40cf029b34f74

**Comment by chapmanb** [comment]
Michele;
Thanks much for the report and sorry about the issues. I've been working on trying to reproduce this so we could provide a definitive fix but haven't been able to do so. However, we've been trying to tackle from a couple of different angles so I'm hoping that upgrading:
```
bcbio_nextgen.py upgrade -u development
```
and re-running will fix the long runtime issue for you. This update gets the latest version of peddy (0.4.1) and also avoids using ensemble calls for inputs, since they can be a bit unusual (coming from multiple callers) and might be triggering issues.

Please let us know if this doesn't fix the problem and happy to continue to work on it to get your analysis finished. Thanks again for the help debugging.

**Comment by miccec** [comment]
Thank you Brad!
I will try this. In the meanwhile, I removed the call to peddy from the main workflow.

**Comment by roryk** [comment]
This should be a non-issue now, thanks!
