### ISSUE TITLE
Unexpected path for upload

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#2386]
Hi,

My GATK variant calling run is failing (at the upload stage, by the looks of it) with the following error:

> ValueError: Unexpected path for upload: {'path': '/home/semlucas/Resequencing_KC_GWAS/Resequencing/work/qc/KSA542/samtools/KSA542-idxstats.txt.bcbiotmp', 'dir': 'qc/samtools'}

The file in question, `/home/semlucas/Resequencing_KC_GWAS/Resequencing/work/qc/KSA542/samtools/KSA542-idxstats.txt.bcbiotmp` doesn't exist, although `/home/semlucas/Resequencing_KC_GWAS/Resequencing/work/qc/KSA542/samtools/KSA542-idxstats.txt` does.

Any ideas on why this file is missing (or why bcbio is looking for a file that doesn't exist)?

Thanks,
Bennet

**Comment by chapmanb** [comment]
Bennet;
Thanks for the report and apologies about the issue. It appears as if bcbio found a temporary file (used when copying/staging) that then got cleaned up. This could happen if running on a shared filesystem and it had not yet cleared the file. If you re-run your analysis in place it should avoid picking this up (since it's gone now) and finish the upload cleanly. I also pushed a fix to development to avoid this happening in the future. Thank you again for the report and hope all works cleanly for you now.
