### ISSUE TITLE
haplotypecallerspark OOM issues on rna-seq variant pipeline

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2390]
Hello, I running a re-analysis of about 400 rna-seq samples and added variant calling to the config.  I'm currently using the stable version of bcbio. I'm running an ubuntu instance on google, 96 cores, 360 GB memory, all the transcript tools run fine the variant calling is throwing alot of errors, im not familiar enough with the new spark gatk integration to know where to start on this one, any help would be great.

Config is:

# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    metadata:
      batch:
      phenotype:
    genome_build: hg38
    algorithm:
      aligner: hisat2
      adapters: [truseq, polya]
      tools_on: [qualimap_full, gemini_allvariants]
      tools_off: [gemini]
      vcfanno: [gemini]
      variantcaller: [gatk-haplotype]
      effects: snpeff
      expression_caller: [stringtie, sailfish, salmon]
      transcript_assembler: [stringtie]
upload:
  dir: ../final

system config:

resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 2G
    cores: 16
    jvm_opts: ["-Xms750m", "-Xmx2500m"]
  gatk:
    jvm_opts: ["-Xms500m", "-Xmx2500m"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx2500m"]
  qualimap:
    memory: 4g
  express:
    memory: 4g
  dexseq:
    memory: 4g
  macs2:
    memory: 4g
  seqcluster:
    memory: 4g

i lowered all the memory limits to what is shown but am still getting the same issues.  my output is attached.
[nohup.out.txt](https://github.com/bcbio/bcbio-nextgen/files/1973347/nohup.out.txt)

**Comment by roryk** [comment]
Hi Patrick,

Sorry about that, it looks like not enough memory is getting allocated to GATK, so it is failing. If you search that log file for 'Java heap space' you can see that happens, and then a bunch of the other processes fail because they are killed. If you bump up the memory allocated to GATK it should fix the issue.

**Comment by PatrickJReed** [comment]
Thanks, in the system config, are the gatk memory settings per core? or total?
gatk:
    jvm_opts: ["-Xms500m", "-Xmx2500m"]

**Comment by chapmanb** [comment]
Patrick;
Sorry about the continued problems. If you further increase memory allocated to GATK, by trying, say 8g, bcbio should automatically scale down the cores used. It would be useful to see if that helps avoid the issue. From the logs it's a bit hard to tell if Spark is hitting memory or disk access issues since it's complaining about both and I'm not sure what's a cause or a symptom.

Apologies, this is so problematic. Both the RNA-seq and HaplotypeCallerSpark bits are new functionality we're working on and will be attempting to scale better in the future. Thanks for the help debugging this.

**Comment by PatrickJReed** [comment]
No worries, just happy for the help.  I upped the mem to 8g and am getting a similar crash.
[nohup4.out.txt](https://github.com/bcbio/bcbio-nextgen/files/1976171/nohup4.out.txt)

**Comment by chapmanb** [comment]
Patrick;
Thanks for continuing to help debug. From the log it appears as if you're making more progress, so moving in the right direction. Your machines appear to be pretty high memory since giving 8gb/core doesn't scale down core usage at all. As before, it's hard to tell if it is memory or disk from 16 simultaneous cores reading/writing.

What type of resources do your machines have? Can you scale up memory more to see if you can reduce total core usage? Maybe try bumping to 16Gb/core as a test. Additionally looking at top as 
before would help differentiate if you're hitting memory problems or just stressing out the disk too much.

My way to debug this would be to adjust until we can make it work then determine how less stringent requirements can be made to work on your system. Thanks again for the patience and work debugging.

**Comment by PatrickJReed** [comment]
Hi Brad,
The instance has 96 cores, 360 GB, ill scale up to 16g/core and see how it goes, thanks so much for helping with this.

**Comment by PatrickJReed** [comment]
Hi Brad, i've updated from the stable to development, and tried both 16g and 32g for gatk on both stable and development, still having the same issues.  Most recent run was with system config:

  default:
    memory: 4G
    cores: 16
    jvm_opts: ["-Xms500m", "-Xmx4
[bcbio-nextgen-debug.log.txt](https://github.com/bcbio/bcbio-nextgen/files/1989559/bcbio-nextgen-debug.log.txt)
g"]
  gatk:
    jvm_opts: ["-Xms500m", "-Xmx16g"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx4g"]
  qualimap:
    memory: 4g
  express:
    memory: 4g
  dexseq:
    memory: 4g
  macs2:
    memory: 4g
  seqcluster:
    memory: 4g

I have attached my debug log.  During this last run, total memory usage never went over 200g out of 360g available.

**Comment by chapmanb** [comment]
Patrick;
Sorry this is continuing to fail. I wish I had a good answer for you but my only suggestion is to turn down cores and turn up memory until you can eventually make it work and then we can try to walk back from there to figure something that is reasonable. This is way more memory than it should need but what I don't know is if it's causing some kind of filesystem issue by running with 16 cores. Did the 32g run scale back from 16 cores and still fail in the same way?

If we can't make it work with less cores my next suggestion would be to try and produce a small example that fails in this way and we could report to the GATK team to see if they have any insight.

Sorry I know this is unsatisfying help but I'm not positive what to suggest with this failure. Hope this helps some.

**Comment by rdocking** [comment]
As a quick trip report - I was having similar issues, that were a bit sporadic. My problematic sample got through with a config like this:

```
resources:
  default:
    memory: 3G
    cores: 32
    jvm_opts: ["-Xms800m", "-Xmx3600m"]
  gatk:
    memory: 3G
    cores: 32
    jvm_opts: ["-Xms800m", "-Xmx3600m"]
```

Which led to memory requests like this:

```
[2018-05-10T16:10Z] ccgihpc.hpc.bcgsc.ca: Resource requests: gatk, vardict; memory: 3.00, 3.00; cores: 32, 32
[2018-05-10T16:10Z] ccgihpc.hpc.bcgsc.ca: Configuring 3 jobs to run, using 32 cores each with 96.1g of memory reserved for each job
```

And a GATK call like this:

```
[2018-05-10T16:12Z] eccfx01n3: export SPARK_USER=rdocking && unset JAVA_HOME && 
export PATH=/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/bin:$PATH && 
gatk-launch --java-options '-Xms800m -Xmx94349m -Djava.io.tmpdir=/projects/karsanscratch/rdocking/KARSANBIO-1390_rna_seq_runs/molm13_replicates/work/bcbiotx/tmpZHeHfM' 
HaplotypeCallerSpark 

... etc ...
```

Watching the job with `top`, it looked like it was using close to the 90G of RAM throughout. This one eventually finished, but then I ran into #2375 

I'm going to try a few more things on my end overnight to see if I can get a cleaner run.

**Comment by chapmanb** [comment]
Rod -- thanks for the report and testing different configuration parameters. I'm sorry I can't help much from afar without a reproducible case but am open to tweaking what bcbio does to provide a more consistent, working, experience here. Thanks to everyone for working through these pain points with RNA-seq calling.

**Comment by PatrickJReed** [comment]
Thanks for the help, so far I am making progress, I had a suspicion that something was buggy on the vm i was using so i moved my drive to a fresh vm, a clean bcbio development install, with 64 cores and 256g memory. I altered to system config as Rod suggested, now using:

resources:
  default:
    memory: 3G
    cores: 32
    jvm_opts: ["-Xms800m", "-Xmx3600m"]
  gatk:
    memory: 3G
    cores: 32
    jvm_opts: ["-Xms800m", "-Xmx3600m"]

When I restarted bcbio with the command:
bcbio_nextgen.py -n 32 ../config/Analysis.yaml &

I immediately began seeing the same error messages, Not enough space to cache rdd_... in memory!

So I re-started bcbio with the command:
bcbio_nextgen.py ../config/Analysis.yaml &

without core specification everything is currently running smoothly, and i have for the first time an actual, viewable, vcf in bcbiotx


patrickreed@bcbio-metapsych:/mnt/disks/metapsych/Analysis/work$ sudo ls bcbiotx/*
bcbiotx/tmpHBSW42:

bcbiotx/tmpmPfTvb:
14501_1_P5_S8_R1_001-gatk-haplotype.vcf.gz  root

bcbiotx/tmpRcBlGI:

The problem now is resource utilization, its really low.
<img width="1416" alt="screen shot 2018-05-11 at 9 02 36 am" src="https://user-images.githubusercontent.com/4350664/39934331-50fc1faa-54fa-11e8-81fd-3ccd6ad0e2b1.png">

One thing i noticed in the log file is that the inital java gatk Haplotypecaller call shows up like this:

[2018-05-11T15:34Z] GATK: HaplotypeCaller
[2018-05-11T15:34Z] Using GATK jar /usr/local/share/bcbio/anaconda/share/gatk4-4.0.3.0-0/gatk-package-4.0.3.0-local.jar
[2018-05-11T15:34Z] Running:
[2018-05-11T15:34Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms727m -Xmx3272m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/disks/metapsych/Analysis/work/bcbiotx/tmpmPfTvb -jar /usr/local/share/bcbio/anaconda/share/gatk4-4.0.3.0-0/gatk-package-4.0.3.0-local.jar HaplotypeCaller -R /usr/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /mnt/disks/metapsych/Analysis/work/align/14501_1_P5_S8_R1_001/14501_1_P5_S8_R1_001-sort-dedup.splitN.bam -L /mnt/disks/metapsych/Analysis/work/bedprep/ref-transcripts-rnaseq_clean.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 --output /mnt/disks/metapsych/Analysis/work/bcbiotx/tmpmPfTvb/14501_1_P5_S8_R1_001-gatk-haplotype.vcf.gz

specifically the -Xmx is -Xmx3272m

previously, when i called bcbio with a -n of 32 or 64 the initial call would be something like:

[2018-05-10T21:09Z] GATK: HaplotypeCallerSpark
[2018-05-10T21:09Z] Using GATK jar /usr/local/share/bcbio/anaconda/share/gatk4-4.0.3.0-0/gatk-package-4.0.3.0-local.jar
[2018-05-10T21:09Z] Running:
[2018-05-10T21:09Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms500m -Xmx45864m -Djava.io.tmpdir=/mnt/disks/metapsych/Analysis/work/bcbiotx/tmpAGP6GY -jar /usr/local/share/bcbio/anaconda/share/gatk4-4.0.3.0-0/gatk-package-4.0.3.0-local.jar HaplotypeCallerSpark --reference /usr/local/share/bcbio/genomes/Hsapiens/hg38/ucsc/hg38.2bit --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /mnt/disks/metapsych/Analysis/work/align/20026_1_P5_S9_R1_001/20026_1_P5_S9_R1_001-sort-dedup.splitN.bam -L /mnt/disks/metapsych/Analysis/work/bedprep/ref-transcripts-rnaseq_clean.bed --interval-set-rule INTERSECTION --spark-master local[16] --conf spark.local.dir=/mnt/disks/metapsych/Analysis/work/bcbiotx/tmpAGP6GY --annotation ClippingRankSumTest --annotation DepthPerSampleHC --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 --output /mnt/disks/metapsych/Analysis/work/bcbiotx/tmpAGP6GY/20026_1_P5_S9_R1_001-gatk-haplotype.vcf

with -Xmx of -Xmx45864m

should this be calling java / gatk with an Xmx of 46g when my system config was setting the -Xmx for both java and gatk to 3g?

**Comment by chapmanb** [comment]
Rod and Patrick;
Thanks again for all of this. I've been working on this and pushed a version of GATK HaplotypeCalling that splits the jobs by chromosomes. It won't be any faster right now since it does them serially, but reduces the amount of work for each step. I was hoping this would allow it to power through each component before running into the issues you're hitting. If you could update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
and re-try it would be helpful to know if this improves things.

Patrick, running without `-n` uses a single core and won't parallelize variant calling. So it'll work but take unreasonably long. Regarding heap size, `-Xmx` is setting that in the bcbio runs, so the default without setting is 32g but it's not a hard limit. I know there are some weirdnesses that can happen around the 32Gb size so it could be useful experiment to try setting below (say, 8 cores with 3Gb each) to see if that has any impact.

Hope the by-chromosome approach helps power through this issue. Thanks again for all the help debugging this.

**Comment by PatrickJReed** [comment]
Update: 

Splitting is working great, and i'm no longer getting any OOM errors even with full core usage.  A new error has occurred from the FixVcfHeader though, please advise if you would like me to open a new issue.  I attached the debug log.
[bcbio-nextgen-debug.txt](https://github.com/bcbio/bcbio-nextgen/files/2032419/bcbio-nextgen-debug.txt)

**Comment by rdocking** [comment]
@PatrickJReed  - that's the same one we're seeing over at #2375

**Comment by PatrickJReed** [comment]
@rdocking Glad this isn't a new issue, thanks.  Original OOM has been solved so I'm going to close this issue.
