### ISSUE TITLE
NA12878-exome-eval error: "realign specified but it is not supported for GATK4." 

### ISSUE THREAD

**Issue by raonyguimaraes** [bcbio/bcbio-nextgen#2395]
Hi there,

I'm trying to run the NA12878-exome-eval pipeline:

mkdir -p NA12878-exome-eval
cd NA12878-exome-eval
wget https://raw.github.com/bcbio/bcbio-nextgen/master/config/examples/NA12878-exome-methodcmp-getdata.sh
bash NA12878-exome-methodcmp-getdata.sh
cd work
bcbio_nextgen.py ../config/NA12878-exome-methodcmp.yaml -n 8

I'm getting the following error:

ValueError: In sample NA12878-1, realign specified but it is not supported for GATK4. Realignment is generally not necessary for most variant callers.

I tried registering the old GATK 3.8 with:

gatk-register GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar 

But I'm still getting the same error after that.

ValueError: In sample NA12878-1, realign specified but it is not supported for GATK4. Realignment is generally not necessary for most variant callers.
****

What could be wrong here?

Kind Regards.

**Comment by chapmanb** [comment]
Raony;
Sorry about the issues running this example. bcbio moved to using GATK4 by default, which no longer supports realignment. You can either adjust the configuration to set `realign: false` or force use of GATK3 with `tools_off: [gatk4]`, which should hopefully get it running.

More generally, apologies about the flux in these examples. We're actively moving to using CWL for bcbio pipelines and collecting the examples and validations in repo so that we can continue to migrate and test them as we move forward (instead of them being more historical artifacts of validations done at different timepoints, as we have now):

https://github.com/bcbio/bcbio_validation_workflows

This is all still active and in progress but I hope the experience will be easier going forward.

If you're just looking to run an exome analysis on your own data, happy to offer any pointers on setting your own YAML for processing.

Thanks again for the report and hope this helps.

**Comment by raonyguimaraes** [comment]
Hi Brad, 

Thanks a lot, that makes total sense! 

I will test with tools_off: [gatk4]

Will also start playing with the validation_workflows!

Regards,
