### ISSUE TITLE
scripts/*.py: /usr/bin/env python -Es  : "not found"

### ISSUE THREAD

**Issue by smoe** [bcbio/bcbio-nextgen#2435]
works:
```
$ /usr/bin/env python -Es
Python 2.7.15 (default, May  1 2018, 05:55:50) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
but when this is the shebang line of a script:
```
$ head -n 1 ./scripts/bcbio_nextgen.py 
#!/usr/bin/env python -Es
```
not so:
```
$ ./scripts/bcbio_nextgen.py 
/usr/bin/env: ‘python -Es’: No such file or directory
```
This is apparently a well-known difference between BSD systems (like our Macs) and Linux. The "-Es" is something you want, right? I am a bit shocked, I must admit. It feels like such bits should have been homogenized across POSIX-like OSes some 30 years ago. On Linux, env is given by the GNU coreutils and over there, a very recent thread I could find on their mailing list about it: https://lists.gnu.org/archive/html/coreutils/2018-06/msg00080.html

For the Debian packaging I think I will substitute this with `#!/usr/bin/python -Es` as I need to touch this because of the two versions of Python, anyway.

**Comment by chapmanb** [comment]
Steffen;
Thanks for the heads up on the problem. During the bcbio install, `/usr/bin/env python` should get converted into the full path to the python used in installing it. This should point at the conda python installed with bcbio rather than the system python. In what cases do you end up with `/usr/bin/env` in the installed `bcbio_nextgen.py` executable? We could probably try and debug why that is happening and fix there instead. We definitely want the `-Es` to keep the bcbio python as isolated as possible, but hopefully can make it compatible across systems through the install process. Thanks again.

**Comment by smoe** [comment]
Er, sorry for the noise, I had executed the files in ./scripts directly. The installed files have the shebang line substituted just like you described.
