### ISSUE TITLE
Including piRNA quantification in smallRNAseq pipeline

### ISSUE THREAD

**Issue by mshadbolt** [bcbio/bcbio-nextgen#2439]
Hi guys

More of a feature request than an issue but I was wondering if there is a reason why piRNAs aren't currently included in the smallrnaseq .gtf file (`~/bcbio-nextgen/data/genomes/Hsapiens/hg19/srnaseq/srna-transcripts.gtf`). It would be great if they were included as part of seqcluster quantification in the srnaseq pipeline.

thanks
Marion

**Comment by lpantano** [comment]
Hi,

Thanks for the reminder.


I removed that because the server was down, but I’ll add it again, you can change the hg19 manually by doing this:

# wget http://www.regulatoryrna.org/database/piRNA/download/archive/v1.0/bed/piR_hg19_v1.0.bed.gz
# zcat piR_hg19_v1.0.bed.gz | awk '{print $1"\t.\tpiRNA\t"$2"\t"$3"\t.\t"$6"\t.\tname "$4";"}' >> srna-transcripts.gtf
      
I hope this help.

Cheers

**Comment by roryk** [comment]
Hi @lpantano,

I see v2.0 are out for these:

http://www.regulatoryrna.org/database/piRNA/download/archive/v2.0/

Do you think switching to 2.0 makes sense? I also see the archive is back up, so we could just turn it back on in cloudbiolinux. Which one do you think we should do?

**Comment by roryk** [comment]
Also, I see the hg38 piRNA installation is using the coordinates from hg19-- do we need to lift those over?
