### ISSUE TITLE
regarding writing configuration file

### ISSUE THREAD

**Issue by MurliNair** [bcbio/bcbio-nextgen#2451]
Hi Brad, 
I need your advise on setting up a bcbio pipeline for two cancer genomes and a normal   I have sequenced. I have them has several fastq files. Here is an one set
2_mucosal_normal_ATGTCA_AC2YF4ACXX_L006_001.R1.fastq.gz
2_mucosal_normal_ATGTCA_AC2YF4ACXX_L006_001.R2.fastq.gz
2_mucosal_normal_ATGTCA_AC2YF4ACXX_L007_001.R1.fastq.gz
2_mucosal_normal_ATGTCA_AC2YF4ACXX_L007_001.R2.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L001_001.R1.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L001_001.R2.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L002_001.R1.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L002_001.R2.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L003_001.R1.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L003_001.R2.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L004_001.R1.fastq.gz
2_mucosal_normal_ATGTCA_BC2MNFACXX_L004_001.R2.fastq.gz

Similarly I have two more sets (normal and another tumor). 
I have the following questions:
1. Do I need to combine the fastq files and specify the combined fastq file in the YAML config file, or can I specify multiple fastq files? 
2. I also have aligned these to hg38 by running bwa mem outside the pipeline and I have the merged bam file, so can I use that bam file for variant analysis using the bcbio pipeline or do I have to start with fastq file as you have in the cancer-normal analysis? 
3. Since I have aligned it to hg38, I should have the reference genome installed  here 
/local/share/bcbio/genomes/Hsapiens correct? 
4. Since on my system bcbio is installed at /work/local/ 
when I run 
 ./bcbio_nextgen_install.py upgrade --genomes hg38 
I have to specify the target correct? 
When I ran the upgrade without specifying the target it installed in the folder I ran the command.  

Many thanks and appreciate your help. 
Cheers../Murli

**Comment by chapmanb** [comment]
Murli;
Thanks for the questions:

1. You do have to merge the fastqs prior to feeding into bcbio and we have a script, `bcbio_prepare_samples.py` to help with this:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#multiple-files-per-sample

2. You can use pre-aligned BAM files by setting `aligner: false`. Depending on how you ran these you may need to fix the read groups and otherwise clean up the inputs and we provide a `bam_clean` argument to help with this:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

3. If you aligned to hg38 you would need to have that installed in bcbio. It's not totally clear the exact path to your bcbio installation, but you're right that it will be present under the `genomes` directory.

4. I'm not sure exactly what is going wrong here, could you provide more details? bcbio shouldn't install anything in the current directory other than creating temporary files for the install process. The command you posted should work to install inside the directory bcbio is present in.

Hope this helps.

**Comment by MurliNair** [comment]
Hi Brad,
bcbio is installed in /work/local 
[mnair@genomics cancerGenomics]$ ls -l /work/local/
total 36
drwxrwxr-x. 2 mnair mnair 20480 Jan  9  2018 bin
drwxrwxr-x. 2 mnair mnair     6 Jan  9  2018 local_install
drwxrwxr-x. 3 mnair mnair    27 Jan  9  2018 share
I ran the following to install hg38
./bcbio_nextgen_install.py upgrade --genomes hg38
I ran it from 
/home/mnair/Documents/workspace/research/cancerGenomics

Since the my bcbio installation has the genomes here
[mnair@genomics cancerGenomics]$ ls /work/local/share/bcbio/genomes/Hsapiens/ -l
total 4
drwxrwxr-x. 17 mnair mnair 4096 Jan  9  2018 GRCh37
Do I have to specify the path when I run upgrade? 

Also, in the installation guide it is mentioned that I need to use the script prepare_cosmic.py if I need to install the updated version of the data set. Is this different from the installation using  bcbio_nextgen_install.py upgrade --genomes hg38, could you please help clarify this for me? 

Thanks for your kind help. 
Cheers../Murli

**Comment by chapmanb** [comment]
Murli;
Thanks for the additional questions. You don't have to specify the path location when running upgrade. bcbio should remember the location from previous successful installs and add the new genome to the same location. `prepare_cosmic.py` is only for installing COSMIC variant data, so is a supplemental process on top of the GRCh37 or hg38 install. It is unfortunately a separate additional step since we're not allowed to redistribute the VCFs. It's not required unless you plan to annotate with COSMIC for somatic calling. Hope this helps.

**Comment by MurliNair** [comment]
Thanks Brad for your comments. I am not sure why the upgrade command install the genome (hg38) in the directory the command is executed from and not in the bcbio location. 
It created a directory named upgrade in the directory I ran the upgrade command. The upgrade directory has the following folders.
[mnair@genomics cancerGenomics]$ pwd
/work/mnair/research/cancerGenomics
[mnair@genomics cancerGenomics]$ cd upgrade/
[mnair@genomics upgrade]$ ls -l
total 4
drwxrwxr-x. 23 mnair mnair 4096 Jul 30 14:43 anaconda
drwxrwxr-x.  2 mnair mnair   10 Jul 30 14:43 config
drwxrwxr-x.  2 mnair mnair   39 Jul 30 14:43 galaxy
drwxrwxr-x.  3 mnair mnair   30 Jul 30 14:43 genomes
drwxrwxr-x.  2 mnair mnair   10 Jul 30 14:43 manifest

Is there an environment variable I need check? 

Thx  for your help. ../Murli

**Comment by chapmanb** [comment]
Murli;
Thanks for following up. Apologies for not spotting the issue earlier. When running the update you should use the installed `bcbio_nextgen.py`, rather than the `bcbio_nextgen_install.py` script, which is no longer needed. So your command should be:
```
bcbio_nextgen.py upgrade --genomes hg38
```
and it'll install within your existing installation. Hope this gets everything working as expected for you.

**Comment by MurliNair** [comment]
Brad, 
I got  a non-zero status when I ran the upgrade. Should I be concerned? The following is the message I received. 
=====================
subprocess.check_output(["bash", run_file])
  File "/work/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/work/local/share/bcbio/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 6
=======================
The entire output is linked below. 
http://www.bioinformatics.iusb.edu/errors/nohup_bcbioUpgrade_out.txt

**Comment by chapmanb** [comment]
Murli;
Sorry for the upgrade problems and thanks for the detail report. This looks like it hit an intermittent error with Broad's FTP server:
```
--2018-07-31 12:24:01--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/hg38//Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi
           => ‘variation/Mills_and_1000G_gold_standard.indels.vcf.gz.tbi’
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... 
Login incorrect.
```
It will report this error when the server gets overloaded. A restart should pick up where it left off, hopefully download this file without issues and continue on. Fingers crossed restarting gets you a clean upgrade.

**Comment by MurliNair** [comment]
Thanks, I shall rerun the upgrade and let you know
Cheers..../Murli

**Comment by roryk** [comment]
Should be all set, this is a common issue with the Broad server. Thank you!
