### ISSUE TITLE
Coverage in multiqc report: is it coming from mosdepth?

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2460]
Hi,

I'm just trying to figure out how the coverage was calculated at the top of the multiqc report. I see a mosdepth command in the log file, assuming it comes from that, although I haven't tried to do this manually. 

Could someone please describe what is meant by "target-genome.bed" as well? I ran whole genome using default whole genome bcbio pipeline. Does this mean coverage in regions with some minimum coverage? Not exactly sure. Thanks - Robert   

[2018-06-17T11:17Z] export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && 
mosdepth 
-t 5 
-F 1804 
-Q 1 
--no-per-base 
--by /hpf/largeprojects/pray/rbaldwin/WGS/HPF/L001_REP/work/coverage/275688_L1/target-genome.bed 
--quantize 0:1:4: /hpf/largeprojects/pray/rbaldwin/WGS/HPF/L001_REP/work/bcbiotx/tmpZU_bdE/275688_L1-variant_regions 
/hpf/largeprojects/pray/rbaldwin/WGS/HPF/L001_REP/work/align/275688_L1/275688_L1-sort.bam

**Comment by chapmanb** [comment]
Robert;
Thanks for the questions, here is the code that calculates average coverage:

https://github.com/bcbio/bcbio-nextgen/blob/b021a12a5935528cef5e1e4e27150ee70d742630/bcbio/variation/coverage.py#L154

which does use the `mosdepth` as input. There are different paths for whole genome versus capture/exome, as you mention. For the command line above, `target-genome.bed` is just a BED file of each chromosome for parallelization purposes. Hope this helps and please let us know if any other information would be useful.

**Comment by chadsmitharc** [comment]
In the multiQC html output, does the 'Cov' column under 'General Statistics' have accurate coverage of exomeseq input sequences? I would like to know my depth of coverage and the values I see are very low.

Running BCBIO(with and without specifying the coverage_interval), mosdepth points to a bed file that has whole genome rather than exomes. That got me thinking it isn't calculating coverage for exomeseq. Thanks!

>
[2019-05-10T19:57Z] export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 16 -F 1804 -Q 1 --no-per-base --by /mnt/fsx/scratch_home/bcbioadmin/PACT225/exomeseq/config/coverage/pact-normal/target-genome.bed --quantize 0:1:4: /mnt/fsx/scratch_home/bcbioadmin/PACT225/exomeseq/config/bcbiotx/tmpizx_6cxs/pact-normal-variant_regions /mnt/fsx/scratch_home/bcbioadmin/PACT225/exomeseq/config/align/pact-normal/pact-normal-sort.bam 

-bash-4.2$ head /mnt/fsx/scratch_home/bcbioadmin/PACT225/exomeseq/config/coverage/pact-normal/target-genome.bed
chr1	0	248956422
chr2	0	242193529
chr3	0	198295559
chr4	0	190214555
chr5	0	181538259
chr6	0	170805979
chr7	0	159345973
chr8	0	145138636
chr9	0	138394717
chr10	0	133797422
-bash-4.2$

**Comment by dauss75** [comment]
Interested in this question so adding a few thoughts.

I think that the Cov is from mosdepth although the bed file for region of interest (ROI) is often not exactly what you provide in the yaml file, but rather it excludes some ROI if that is not covered at all in the bam I think.  If you go to the ~/work/coverage/ directory, then you can see the coverage per each ROI in sample.name-variant_regions.regions.bed.gz

For example,
1       2489159 2489278 1350.25
1       2489776 2489912 1020.01
1       2491256 2491422 1052.57
1       2492057 2492158 1326.21
1       2493106 2493259 728.11

**Comment by roryk** [comment]
@chapmanb do you know the answer to this off the top of your head? I can look at the code if not.

**Comment by roryk** [comment]
Thank you!
