### ISSUE TITLE
how multiqc report bcbio % duplicated reads was calculated?

### ISSUE THREAD

**Issue by zzupmc** [bcbio/bcbio-nextgen#2461]
Hi, 

thanks for developing such a great tool. After I ran an analysis, in the multiqc report html file, I found two columns, one is bcbio % duplicated reads , the other is fastqc % duplicated reads. For my sample, these two is quite different. My data is from a tumor Amplicon panel. I checked the log file, and cannot find the information for how  bcbio % duplicated reads was calculated. Please help me. 

Thanks,
Hongen

**Comment by lpantano** [comment]
Hi,

In this case, duplicated reads come from the samtools stats command and it is parsed from this line in the code:

https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/qc/samtools.py#L64 

What is the difference are you seeing? What pipeline are you using in bcbio? In theory these two tools uses the same input, you can make a grep in the bcbio-nextgen-command.log to check the input of each of them and let us known just in case we are missing something.

Cheers

**Comment by zzupmc** [comment]
Hi Lorena and Brad,

thanks for your explanation. For my case- Agilent clearseq cancer panel, bcbio % duplicated reads is about 90%, and I checked FastQC results (ran by myself with default setting), percent remaining if deduplicated 13%. They are quite close. But in the multiqc report of bcbio,   fastqc % duplicated reads is 40%. For fastqc, did you use a different threshold for defining a duplicate? 

Hongen

**Comment by chapmanb** [comment]
Hongen -- as I mentioned above, I suspect the difference is due to bcbio downsampling the BAM file before running in FastQC. Since it's only using a portion of the file, it won't be the same as what you get from running manually on the full BAM. Beyond that bcbio just calls fastqc without any special tweaks. I'd suggest ignoring the fastqc summary stats in MultiQC because of the downsampling. Hope this helps.
