### ISSUE TITLE
Ploidy not set for HaplotypeCaller in joint (GVCF) calling mode

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2471]
Hello,

I've recently started using HaplotypeCaller in GVCF mode. I've noticed in the bcbio-commands.log files that the option "-ploidy 1" is included into the HaplotypeCaller commands in the "pooled calling" scenario (where all the sample BAM files are passed as inputs), but it is not included when calling variants in the "joint calling" manner, i.e. when the option "jointcaller: gatk-haplotype-joint" is added to the YAML config file.

The result of this is that variants are called with diploid settings, although I'm working on a haploid organism and I've specified "ploidy: 1" in the YAML config file.

**Comment by chapmanb** [comment]
Thanks much for this issue. Apologies, I hadn't realized that GenomicsDB now supports non-diploid inputs. Joint calling was previously restricted to only diploid calls due to this limitation but looks to be working now. If you update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
and re-run the variant calling and joint calling it should now respect your input ploidy. Thanks again for this discussion and the heads up.
