### ISSUE TITLE
Multiqc report

### ISSUE THREAD

**Issue by sluke123** [bcbio/bcbio-nextgen#2479]
is it possible to include extra columns in the general statistics table -
There is now
QualiMap | ≥ 50X | Fraction of genome with at least 50X coverage
but also
QualiMap | ≥ 500X | Fraction of genome with at least 500X coverage
QualiMap | ≥ 1000X | Fraction of genome with at least 1000X coverage
QualiMap | ≥ 2000X | Fraction of genome with at least 2000X coverage

**Comment by chapmanb** [comment]
Sally -- thanks for bringing this up. @vladsaveliev I know you'd previously implemented this coverage for higher depths as part of post-processing the bcbio MultiQC report. I'd like to move this into bcbio, ideally picking a useful range based on the sample depth. Do you have pointers to how this was done previously? Was it all within QualiMap or done externally? In MultiQC we can specify the QualiMap thresholds (https://github.com/ewels/MultiQC/blob/2ccda53608771d73a3392841d5a44114daed772a/multiqc/modules/qualimap/QM_BamQC.py#L56) but I wasn't sure if this was the correct path to go down.

**Comment by vladsaveliev** [comment]
Hi Sally, Brad,

Bcbio can do that already. See: https://github.com/bcbio/bcbio-nextgen/pull/2048
The idea is to pass the MultiQC parameters for the Qualimap module (`qualimap_config`) via the bcbio yaml in the resources section:

```
resources:
  multiqc:
    options: ["--cl_config", "'qualimap_config: { general_stats_coverage: [20,40,200] }'"]
```

**Comment by chapmanb** [comment]
Vlad;
Thanks for this. I'm cool with tweaking it and my general idea is to set this directly within bcbio depending on the existing depth, to avoid users needing to explicitly determine the right setting and then set in resources. I primarily wanted to confirm that this was the approach you took in post-proc so I could replicate your previous behavior inside of bcbio. Did you have any existing logic to pick a setting for this, or just always do the deeper coverage as well? Thanks again.

**Comment by vladsaveliev** [comment]
Ah, sorry, not enough coffee, missed the part in your question about automatically picking the range based on depth. Of course, that sounds like a good idea to move into bcbio. Here is the logic:
https://github.com/AstraZeneca-NGS/NGS_Reporting/blob/master/ngs_reporting/bcbio/multiqc.py#L77-L89

Basically we start with the range of thresholds of [1, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000], and evaluate all thresholds up to current sample depth, plus one more. For example, if you have a sample of depth 570x, we will evaluate [1, 5, 10, 20, 50, 100, 200, 500, 1000].

Then, since MultiQC has a logic of "hidden" columns, by default in the report we show only the thresholds up to 20, plus those that are closest to sample depths, and set the rest as hidden. So for the sample of depth 570x, we will show 1, 5, 10, 20, plus 500 and 1000. And if you have multiple samples in a run with different depths, we will account for all of them, so for example for two samples of 570x and 250x, we will show 1-20, 200, 500, and 1000.

MultiQC provides two parameters in `qualimap_config` section in its configuration yaml: `general_stats_coverage` and `general_stats_coverage_hidden`. So in the example above, we would populate MultiQC config as:

```
qualimap_config:
   general_stats_coverage: 1, 5, 10, 20, 50, 100, 200, 500, 1000
   general_stats_coverage_hidden: 50, 100
```

Let me know if that doesn't make sense. I help to implement it in bcbio (can try to implement the logic more simply and put comments that make sense).

Vlad

**Comment by chapmanb** [comment]
Vlad;
Awesome, that's exactly what I was thinking of. This is perfect. It would be brilliant if you have time/willingness to implement in bcbio. If not, I can pick it up from all this. Thanks again.

**Comment by vladsaveliev** [comment]
Brad, create a PR with this: https://github.com/bcbio/bcbio-nextgen/pull/2483

**Comment by chapmanb** [comment]
Sally, Vlad ported over the previous logic to bcbio so we'll now have it in the latest development and next release. Thanks Vlad for doing this, and thanks Sally for identifying we're missing this.
