### ISSUE TITLE
Dream validation set 4 download?

### ISSUE THREAD

**Issue by davidmasica** [bcbio/bcbio-nextgen#2486]
Hello, 

I see the download script and .yaml files for downloading and validating against DREAM's synthetic challenge set 3. However, for set 4 there is a .yaml file and no download script. Is it possible to include the download script for this set?

**Comment by chapmanb** [comment]
David;
Apologies, but the DREAM synthetic 4 dataset is controlled access, since it's based off of a patient sample, so we're not able to setup automated download scripts. DREAM synthetic 3 is fully synthetic and publicly available, hence the automation we have in place for that.

Unfortunately I also don't know of any location where the controlled access DREAM datasets are still available for download. So I don't even have a manual way to point you to get the synthetic 4 dataset.

Practically we've been working on putting together new validation standards to fill the gap left by the DREAM challenge ending and have some mixture data:

https://github.com/bcbio/bcbio_validation_workflows#somatic-genome-in-a-bottle-mixture

and tumor-only truth sets and data:

https://github.com/bcbio/bcbio_validation_workflows#somatic-low-frequency-variants

That might be useful. Hope this helps.

**Comment by davidmasica** [comment]
Thank you for the quick and detailed response... this is most helpful!

**Comment by roryk** [comment]
Answered, closing as part of an issue clean-up. Thank you!
