### ISSUE TITLE
somatic variant calling with RNA-seq data 

### ISSUE THREAD

**Issue by deaytan** [bcbio/bcbio-nextgen#2521]
In order to call somatic variations using RNA-seq data, do you have any recommended configuration file? And is it fine to do somatic variant calling using RNA-seq data with your variation algorithm?

**Comment by chapmanb** [comment]
Thanks for the question. Can you provide a bit of clarity but what you mean by somatic variant detection in this case? Are you interested in variants in tumor RNA-seq samples relative to some kind of normal reference? In bcbio, we have basic variant calling enabled as part of the RNA-seq pipeline. This will call variants, with GATK HaplotypeCaller or VarDict from the samples. It includes basic filtering and annotation with RNA editing sites, but not any kind of differential subtraction between samples.

Hopefully that will work for your RNA-seq variant calling needs. RNA-seq variant calling has been a challenge for us due to the lack of truth sets to help tune and provide filtering.

**Comment by deaytan** [comment]
Hi,

Thank you very much for your answer. I tried to add variant calling feature into RNA-seq configuration however, I got an error regarding to BED file:

IOError: Cannot write transcript BED output file /services/tools/bcbio-nextgen/1.0.1/share/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.bed

My configuration file was included in these lines under the algorithm title:

      aligner: star
      quality_format: Standard
      trim_reads: read_through
      adapters: [truseq, polya]
      strandedness: unstranded
      variantcaller: vardict 

Is it the way to call variants for RNA-seq pipeline or am I completely wrong about that?

And for your question, we were originally thinking about subtraction between samples but I think it is not possible with your RNA-seq pipeline I guess. 

In spite of the fact that, what if I run my RNAseq samples with your variation pipeline which is originally for DNAseq samples. Would I do a huge mistake?

**Comment by lbeltrame** [comment]
> In spite of the fact that, what if I run my RNAseq samples with your variation pipeline which is originally for DNAseq samples. Would I make a huge mistake?

As someone who has done it, there are a few caveats you need to bear in mind:

1. You need to align first the RNA with bcbio, then use the GATK's SplitNCigars (name may be inaccurate, I'm going from memory) manually on the final BAM, or you'll get data that will make variant callers to complain.
2. For better sensitivity (as described in a paper a couple of years ago) you may want to extract the unmapped reads from the BAM, map them with BWA, then merge them back in the original BAM. This is because somatic variant calling is affected by the way HISAT2 and other aligners work with RNA.
3. After that, you can treat the sample as "DNA" and use bcbio to run a "regular" somatic analysis along with your reference.
4. If your reference is not RNA, you'll get a lot of variants (indels, in particular) around splice junctions (obviously, you're looking at mRNA that has been already spliced): if you have a transcript table you may want to use the exon and junction data to remove artifacts.
