### ISSUE TITLE
spark error with new gatk4 pipeline

### ISSUE THREAD

**Issue by sxv** [bcbio/bcbio-nextgen#2530]
I'm using the latest development version of bcbio to run tumor/normal pairs. I tried running without specifying multiple cores but still getting the same error. It's hard to debug so hoping someone can help.

```
[October 2, 2018 9:13:00 PM PDT] org.broadinstitute.hellbender.tools.spark.BaseRecalibratorSpark done. Elapsed time: 170.84 minutes.
Runtime.totalMemory()=3320315904
org.apache.spark.SparkException: Job 0 cancelled because SparkContext was shut down
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:820)

... (many more lines of error here) ...

        at org.broadinstitute.hellbender.Main.main(Main.java:289)
18/10/02 21:13:00 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
18/10/02 21:13:00 INFO MemoryStore: MemoryStore cleared
18/10/02 21:13:00 INFO BlockManager: BlockManager stopped
18/10/02 21:13:00 INFO BlockManagerMaster: BlockManagerMaster stopped
18/10/02 21:13:00 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
18/10/02 21:13:00 INFO SparkContext: Successfully stopped SparkContext
18/10/02 21:13:00 INFO ShutdownHookManager: Shutdown hook called
18/10/02 21:13:00 INFO ShutdownHookManager: Deleting directory /tmp/tmpi0fYw_/spark-a5d8461b-c9fb-425c-96a1-7633642dc28b
' returned non-zero exit status 52
```

Any ideas? Thanks.

**Comment by chapmanb** [comment]
Sujay;
Thanks for the report and sorry for the issue. Unfortunately I can't identify a likely error from this section of the traceback. We'd probably need to dig through the full traceback as the Spark errors can get quite buried in the large amount of logging output. If you post it as a gist (http://gist.github.com/) maybe we can spot the issue.

Practically, this is typically due to memory or disk IO issues when running Spark and can be tricky to debug remotely. You can see a similar issue #2037, where we tried to work around the issue by using a different installed Java version.

Do you think you need recalibration for this run? We typically do not use it unless we detect poor quality sequencing and think the recalibration may help. It can be quite computationally expensive and we've found it doesn't impact results in cases where we have good quality inputs.

Hope this helps some with debugging.

**Comment by chapmanb** [comment]
Sujay;
GATK just release 4.0.10.0 (https://github.com/broadinstitute/gatk/releases/tag/4.0.10.0) which re-works Spark memory usage. I'm not positive if this will help with your issue, but it could be worth a try. The latest development version of bcbio supports this so if you update with:
```
bcbio_nextgen.py upgrade -u development
```
you can re-run and test. Hope this helps push your analysis through.

**Comment by sxv** [comment]
will do! thanks as always.
