### ISSUE TITLE
featureCounts in htseq-counts output dir?

### ISSUE THREAD

**Issue by AndreVidas** [bcbio/bcbio-nextgen#2544]
Hi bcbio.

Am I wrong or does the featureCounts output go into the htseq-counts folder?

l. 28 in featureCounts.py: out_dir = os.path.join(work_dir, "htseq-count")?

And if so why is that the case and how can I obtain the htseq-counts results instead? 

Best regards,
André

**Comment by roryk** [comment]
Hi @AndreVidas,

You're right-- it does go to the htseq-counts folder, we swapped over to using featureCounts a while back because it is much faster than htseq-count, and gives similar results. We don't have a way to get the htseq-counts anymore.

If you're looking to do downstream quantification, we recommend using the output from Salmon as it is much more accurate and is not blind to many genes that the align-and-count methods are.
