### ISSUE TITLE
how to configure with CWL the total number of CPUs?

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2553]
Hi Brad, I am just testing CWL and I do not get how to configure the total number of CPU for a run?

https://github.com/bcbio/test_bcbio_cwl/archive/master.tar.gz is also missing the index file for two bam file in the somatic test set (6_100326_FC6107FAAXX_2 and 6_100326_FC6107FAAXX). (just for your information)

```
bcbio_vm.py cwlrun cromwell somatic-workflow --no-container -s lsf -q cpuqueue -n 12
usage: bcbio_vm.py [-h] [--datadir DATADIR]
                   {template,cwl,cwlrun,install,upgrade,run,ipython,ipythonprep,runfn,devel,aws,elasticluster,graph,saveconfig}
                   ...
bcbio_vm.py: error: unrecognized arguments: -n 12
```

**Comment by chapmanb** [comment]
Alessando;
Thanks much for testing this out. CWL and Cromwell runs don't have the same idea of limiting total cores because the run approach is different. The main runner dispatches jobs as they're available and then lets the scheduler decide on allocating them from the queue according to the resources. Cromwell does have a configuration parameter, `concurrent-job-limit` we could use to limit total jobs submitted concurrently, rather than cores, if this approach becomes a problem. It would be useful to know how the approach of just submitting jobs and letting the scheduler handle it works for you, and then determine how best to limit jobs if it causes issues. Thanks much for starting this discussion.
