### ISSUE TITLE
bcbio rnaseq pipeline redirect bgzip fastq to work folder 

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2558]
Dear Team,

Thanks a lot for nice pipelines.
I am working with bcbio rna-seq pipeline using LSF as scheduler and pipeline is trying to create bgzip fastq files in input directory itself. Some times we will be not having write permissions to input fastq directory and pipeline will fail in that case.
Actually, wgs pipeline is creating new directory inside work and placing bgzipped fastq files inside **align_prep** folder.

Could you please let me know is there any way to **redirect bgzipped fastq to work directory**?

Thanks In Advance
Fazulur Rehaman

**Comment by roryk** [comment]
Hi Fazulur,

Sorry about that-- there isn't a way to do that currently. You could work around it by copying the files to somewhere where you do have write permissions, or linking to the files. It kind of makes sense to keep the files together since they are just bgzipped versions of the original files, but we could also stick these into `align_prep`. Brad, what do you think?

**Comment by Fazulur** [comment]
Hi roryk,

Thanks for your quick response. I will go with symbolic links instead of copying data.

Thanks & Regards
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur and Rory;
My approach in the variant calling pipeline has been to treat everything outside of the work directory as non-writable and create the bgzip files within the work directory. This is also needed for CWL support since we won't have permissions to write to the initial location of files; it enforces only writing to the work directory. So although I agree it would be cleaner to have them prepped in the original directory, practically my vote would be to move to doing it inside the work directory.

**Comment by roryk** [comment]
Hi Brad,

Great-- I'll implement that.

**Comment by roryk** [comment]
Thanks everyone, I implemented this and in the next release bcbio won't write to the original directory anymore, preferring to stick the bgzipped files in `work/fastq`.

**Comment by Fazulur** [comment]
Dear Roryk and Brad,

Thanks a lot for update on moving fastq to work/fastq. 

Thanks & Regards
Fazulur Rehaman
