### ISSUE TITLE
run_peddy fails

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#2575]
Hi there,

this is the yaml file I'm using:
https://gist.github.com/leiendeckerlu/b4e4fd4db05d2aac1a0bff6e835e71b7

and this is the respective error log:
https://gist.github.com/leiendeckerlu/a45f1e491b710965034a4489a44954a8

Not sure if its associated with one of the previously reported peddy errors.

Any idea what's going on here?

Thank you,
Lukas

**Comment by chapmanb** [comment]
Lukas;
Apologies, this was error in 1.1.1 that is fixed in the latest development version. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run in place it should pick up where it left off and correctly skip peddy if no suitable somatic callers are found for extracting germline variants. Sorry again about the problem and hope this gets your analysis finished.
