### ISSUE TITLE
Is s3.amazonaws.com still available ?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2591]
Hi,
I am installing human geneomes data using bcbio's upgrade command. But the connection to https://s3.amazonaws.com/biodata/genomes/hg19-seq.tar.gz failed. I copied the url to browser found that this url got 404 error. Is s3.amazonaws.com still available ?

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. This reference file is still available and I don't have any problems accessing here locally right now. Is this a persistent problem, or could it be due to temporary network instability? If you try to get the file outside of the install:
```
wget --no-check-certificate https://s3.amazonaws.com/biodata/genomes/hg19-seq.tar.gz
```
Does it just report a 404 error or other issues? Thanks much for helping debug.

**Comment by roryk** [comment]
Looks like this was a network issue and should be a non-problem.
