### ISSUE TITLE
effect of installing python ver 3 

### ISSUE THREAD

**Issue by MurliNair** [bcbio/bcbio-nextgen#2621]
Hi Brad, 
If I install python ver 3 would it affect my existing installation of bcbio?
Thanks ../Murli

**Comment by chapmanb** [comment]
Murli;
External python installs of any version should not affect bcbio, since it installs it's own isolated python and tries to not include any external libraries. We're actively moving bcbio to also support (and then move to) Python 3 in the standard install, so the isolated environment will also hopefully be primarily python 3 soon. Hope this helps.
