### ISSUE TITLE
bcbio for high-depth panel of ~20 genes

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2630]
Hi, I noticed that previous post #1715 have discussed this problem, I just want to know how to set the parameters in yaml file to support high-depth (about 2000x) panels covering tens of genes.  First, it seems there are two parameters, coverage_interval and variant_regions, can be used to narrow down the regions to be analysed. Which one should I use? Second, which variant caller is the best choice for panel analysis? I saw that gatk now supports panel analysis, but the previous post recommend vardict. Is there any comparison between gatk to vardict? Thanks in advance.

**Comment by chapmanb** [comment]
Thanks much for the question. For panel sequencing there aren't any specific options to tweak other than setting `variant_regions: your_targets.bed`. It should detect `coverage_interval` based on this so that doesn't need any tweaking. For calling, the GATK versus VarDict difference really depends on what type of sequencing you're doing. GATK HaplotypeCaller is used for germline analyses and VarDict for somatic low frequency calling. From your depth it sounds like a somatic analysis, so VarDict other other supported callers (strelka2, mutect2, octopus) would all be reasonable choices. Hope this helps.

**Comment by lbeltrame** [comment]
Hello @hliu2016,

I've been doing my fair share of  targeted panels in the past. In my experience, Mutect2 and VarDict offer the best results for somatic calling (with Mutect we have a validation rate > 90%). I've noticed that Mutect2 is better for variants at low fraction rather than VarDict, but you then need independent confirmation and/or accurate review of those, depending on the data.

A lot boils down to the minimum allelic fraction that you want to identify: in my experience, anything around 1% can be true, but very hard to validate. Fractions in the range from 3 to 5% are more easily manageable. Anything > 5% is even better.

**Comment by gabeng** [comment]
I can second that the false-detection rate in VarDict rises steeply below 10% AF. Mutect2 seems to be better at that and is also undergoing major improvements. I am looking forward to gatk 4.1. 
A challenge will be to validate the performance of such small panels. Only few giab variants will be located inside target regions. 
@lbeltrame: do you see any advantage in ensemble calling? Is your assessment wrt 5% threshold based on tumor-normal calling or tumor-only?

**Comment by hliu2016** [comment]
@lbeltrame @gabeng 
Thank you for sharing your experience. I am a newbie to mutect2, if it should be used for cancer-normal paired samples?

**Comment by lbeltrame** [comment]
> @lbeltrame: do you see any advantage in ensemble calling? Is your assessment wrt 5% threshold based on tumor-normal calling or tumor-only?

@gabeng 
We use ensemble both for consensus calling (variant called by multiple callers) and union (because some variants we found were only detected by a single variant caller), depending on what we're working on.  The threshold we made is with paired samples in mind: tumor-only data is far noisier (at least last time I've tried) so I would suggest stricter filters and probably higher fractions thresholds.

**Comment by hliu2016** [comment]
@chapmanb @gabeng 
I have just run the variant pipeline using mutect2 and vardict independently on a tumor-onlyl sample. I found that the variants by the two callers is quite different. Overall, mutect2 outputs much more variants than vardict, but their overlap is very few.

**Comment by gabeng** [comment]
That would be very strange. Could you post your config here? How did you compare the variant calls? Did you compare only PASS variants or all variants in a VCF file?
In general, Mutect2 atomizes MNV calls, but retains phasing information in the VCF file. Vardict on the other hand tends to call MNVs. For benchmarking it makes life easier to use reference samples and the built-in validation tools in bcbio.

**Comment by hliu2016** [comment]
@gabeng 
Thanks for your concern. I configure to run mutect2 and vardict at the same pipeline. The yaml file is as below:

> ---
> upload:
>   dir: ./
> details:
>   - files: [../input/L103_R1.fastq.gz, ../input/L103_R2.fastq.gz]
>     description: liuqingfeng
>     metadata:
>       phenotype: tumor
>     analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       mark_duplicates: true
>       min_allele_fraction: 1
>       mixup_check: qsignature
>       platform: illumina
>       quality_format: Standard
>       recalibrate: gatk
>       realign: false
>       effects: snpeff
>       variantcaller:
>         somatic: [mutect2, vardict]
>       variant_regions: /bio/zhengu/Corectical_22.bed
>       svcaller: [cnvkit]
>       remove_lcr: true
>       tools_off: [gemini]
> 

I checked their calls stored in the vcf files, and found very few overlap. I uploaded these two vcf files for your check. Thanks very much.

[vardict.vcf.gz](https://github.com/bcbio/bcbio-nextgen/files/2862945/vardict.vcf.gz)
[mutect2.vcf.gz](https://github.com/bcbio/bcbio-nextgen/files/2862946/mutect2.vcf.gz)

**Comment by hliu2016** [comment]
@chapmanb
Should I turn on the tumoronly_germline_filter option for tumor-only analysis? I think this option corresponds to the LowPriority filter, which is stated to filter germline variant in ExAC and 1000 genomes projects. Thanks in advance.

**Comment by chapmanb** [comment]
Thanks for the question and sharing the files. I did a quick `bcftools isec` overlap of the two files and 2 variants out of 35 VarDict and 55 MuTect2 matches. It also looks as if by eye there are a number of close by variants and single base pair deletions in the passing calls which could be spurious. tumor-only calling definitely has more false positives, especially for low frequency calls. The other strange thing is that the depths are pretty different between the VarDict and MuTect2 calls. It's possible the germline filters will help, although for hg38 require installing a custom version of COSMIC (https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#customizing-data-installation) since we're not allowed to redistribute it.

Hope this helps on digging more into the calling.

**Comment by hliu2016** [comment]
@chapmanb @gabeng 
I made a mistake before, as my input fastq file are from amplicon sequencing. So, I remove the mark duplicate step, and rerun the analysis pipeline. However, the results of these two caller still differ from each other largely. 
The yaml file is now as show:
```
upload:
  dir: ./
details:
  - files: [../input/L103_R1.fastq.gz, ../input/L103_R2.fastq.gz]
    metadata:
      phenotype: tumor
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      mark_duplicates: false
      recalibrate: gatk
      realign: false
      effects: snpeff
      variantcaller: [vardict, mutect2]
      variant_regions: /bio/zhengu/Corectical_22.bed
      ensemble:
        numpass: 2
        use_filtered: false
      remove_lcr: true

```
Mutect2 reports tens of variants, but vardict reports only three variants. There is only one overlap. This really confuses me. 

[mutect2-annotated.vcf.gz](https://github.com/bcbio/bcbio-nextgen/files/2867706/mutect2-annotated.vcf.gz)
[vardict-annotated.vcf.gz](https://github.com/bcbio/bcbio-nextgen/files/2867707/vardict-annotated.vcf.gz)

**Comment by chapmanb** [comment]
Thanks for following up with the re-analysis. A couple of thoughts:

- You are no longer setting `min_allele_fraction` so VarDict calls will cutoff at 10%, removing the lower frequency events you saw earlier. MuTect2 doesn't respect this parameter so will continue to call these.
- The annotated versions do have overlaps with known germline databases (the INFO EPR flag) and all of the VarDict PASS calls here overlap with ESP or ExAC so are likely germline.

If you bring these in line the numbers should be a little closer but you're always going to expect noise with tumor-only calling. If you have any known variants in your samples to calibrate against I think this would give you a better way to evaluate sensitivity/specificity. Hope this helps.

**Comment by roryk** [comment]
Great discussion with some good suggestions made, closing this since I think the discussion ran its course. Thank you everyone!
