### ISSUE TITLE
Small RNA-Seq paired end adapter trimming

### ISSUE THREAD

**Issue by keenhl** [bcbio/bcbio-nextgen#2634]
I am trying to run the small RNA-Seq pipeline with paired end reads.  The adapters are removed from the first reads file and the appropriate cleaned and trimmed files are generated.  However, as far as I can tell, adapters are not being trimmed from the second reads file.  Do I need to specify something additional in the template file (excerpt of file shown below)? 

details:
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirdeep2
    species: hsa
  analysis: smallRNA-seq
  description: sample
  files:
  - sample_R1_001.fastq.gz
  - sample_R2_001.fastq.gz
  genome_build: hg19

**Comment by lpantano** [comment]
Hi,

You have a good config file. bcbio only support single end data for small
RNA seq. The majority of tools work only with the first read only because
it is not clear the advantage of doing pair ends for small RNAs.

Just to make sure that small RNA has the same meaning here, I am talking
about sequencing RNA molecules of 20-40 nt long. Is that your case?

Thanks



Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th
