### ISSUE TITLE
Bcbio 1.1.2: RNAseq MultiQC report not copied from work dir to final dir

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2640]
Hi, 

This is a bit of minor issue but still would be nice to have fixed:

The RNAseq MultiQC work directory is not copied anymore in bcbio 1.0.2. to the final directory.   
The SV Lumpy MultiQC work directory is copied in bcbio 1.02. to the final directory. 

I did not yet run any WGrS analysis using bcbio1.0.2 so there I don't know if the MultiQC directory is copied to the final directory. 

The RNAseq MultiQC report is present in the work directory, also all the input QC files are present and the log files are present. I could open the MultiQC report. It is just not copied anymore from the work dir to the final dir.

**Comment by chapmanb** [comment]
Wim;
Sorry about this issue. This was a bug in 1.1.2 that's fixed in the latest development version and will be in the 1.1.3 release we're hoping to have at the end of the week. This only happens when run in distributed mode so a workaround if you don't want to upgrade is to re-run the workflow in single core mode and it'll get copied over. Sorry again about the problem and hope this helps.

**Comment by WimSpee** [comment]
Ok thank you for the information. I look forward to the 1.1.3 release.
