### ISSUE TITLE
Checking tool versions when using Bcbio_vm + CWL (Cromwell)

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2663]
Hello,

Previously when using Bcbio_nextgen, the tool versions were written to the file `final/<date>_<batch>/programs.txt`, for the sake of provenance. Is there any equivalent functionality when using Bcbio_vm + CWL (Cromwell)?

**Comment by chapmanb** [comment]
Thanks for the questions. We do have this in the final directory with Cromwell also, although it's in a sample directory not in the `project` directory. You'll have `cromwell_work/final/sample/programs.txt` and `cromwell_work/final/sample/data_versions.csv` that are equivalent to the standard runs.

Sorry for the change in output location, we don't have as much control over outputs with CWL since we're using external runners rather than bcbio itself, so this is something we're continuing to work on.

Hope this works.

**Comment by amizeranschi** [comment]
Thanks for letting me know. Didn't think about checking the sample directories, but I found the `programs.txt` file in the first sample dir. Glad to know this functionality is still available!
