### ISSUE TITLE
Adding a custom genome without a GTF file

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2665]
I was checking out https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#config-custom regarding adding new genomes. Is there a way to work with Bcbio for e.g. RNA-seq transcriptome assembly with cufflinks/stringtie, in a case where there isn't an available GTF file with annotations to start with?

I noticed in https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html?highlight=stringtie#rna-sequencing that cufflinks and stringtie are supported both as transcript assemblers and also for read counting. Will this work to e.g. use the novel assembled transcripts for expression calling, without having to provide an initial GTF file from the start?

Alternatively, would it make sense to assemble novel transcript FASTA sequences from RNA-seq reads, and then map the transcripts to the genome, in order to generate a GTF file? Is this even advisable?

**Comment by roryk** [comment]
Hi @amizeranschi,

We don't have a way to run bcbio's RNA-seq pipeline without an initial GTF file at the moment, unfortunately. If your organism has a gene annotation at all, I'd recommend using that as input and running transcript assembly with Stringtie, cleaning up the annotation outside of bcbio (I recommend using transrate or something similar to score and remove garbage transcripts) and then make a new bcbio genome with that GTF file. If that doesn't exist, you might have to get the initial assembly outside of bcbio. I have some advice on how to do that if you end up going that route, let me know what you decide to do. 

We could theoretically support no GTF file in bcbio to get the initial assembly; the reason why we haven't done it before is it used to be that to create the STAR index you needed to have a GTF file, but now you can provide it on the fly so that is no longer a limitation. Implementing that would be pretty low on a priority list since most folks aren't using bcbio for that. If this is something you think you'll find yourself doing a lot though, let us know.

Hope that helps some, sorry to not have this supported out of the box.

**Comment by amizeranschi** [comment]
Hi @roryk,

Thanks for your reply. There's a genome assembly, but there are no gene or transcript annotations available at the moment and I have zero experience with creating these, so any advice you have about this would be greatly appreciated. 

The only thing I could think of so far is to assemble transcripts from RNA-seq data, map the transcripts to the genome (would a splice-aware tool be required for this?) and somehow generate a proper GTF file from those mapped positions. Not sure how much practical sense this makes yet, as I'd have to read a bit about it.

**Comment by roryk** [comment]
Thanks-- which organism is it?

I would make a hisat2 index from the assembly and run StringTie with no GTF to get the assembled transcripts. I'd do this once for every replicate I had, so don't combine the replicates, do them all separately. Then I'd merge all of the transcripts together with StringTie `--merge` option to get a GTF file of all of the transcripts called in the genome.

After I did that, I would use transrate on that assembled GTF file, and drop all transcripts that don't have support in any sample. A simpler way of doing this would be to take the merged, assembled GTF file, run it through bcbio and then drop any transcript that has low or no TPM.

**Comment by amizeranschi** [comment]
I was having a look at hop (Humulus lupulus) and, at first sight, it doesn't look like much has been done with it so far. 

Thanks a lot for the hints. I'll close this issue for now and reopen later if I run into a dead end.

**Comment by amizeranschi** [comment]
Hello again @roryk,

After a long while, I finally got around to trying this. I created a transcriptome assembly with Stringtie and used Transrate with the paired-end reads. Among other things, this produced a couple of FASTA files: `good-transcripts.fa` and `bad-transcripts.fa`. Should I now discard the bad transcripts altogether?

Is there a way to create a new GTF file from the `good-transcripts.fa` file, using the reference genome? I know that `gffread` can do the opposite (i.e. it can extract a FASTA file with transcripts using a GTF file and a ref. genome), but what about going from the FASTA to GTF?

**Comment by dandanxu** [comment]
Apologies if this is obviously not what you're looking for (I don't know anything about hop genomics), but it looks like there are some gene/transcript annotations available on hopbase - http://hopbase.cgrb.oregonstate.edu/downloadMaskedCascadeHaplotigs.php (GFF3 files at bottom)

**Comment by roryk** [comment]
Thanks Dandan! Good find. @amizeranschi, Dandan's suggestion of using previous-annotated genes is the best way to go if that would work for you-- assembling transcriptomes is hard so if something already exists then using that is almost always a better way to go.

If you want to go with what you are doing, then you'll have to filter your GTF file to not include the transcripts in the bad-transcripts.fa file if you want to drop the bad ones. A simple way to do that would be to take all of the transcripts named in bad-transcripts.fa and then do a `grep -v -f bad-transcripts.txt your-gtf-file` which will give you back a GTF file without any of those transcripts in it.

**Comment by amizeranschi** [comment]
Thanks a lot for the Hopbase link and for the transcript filtering instructions.
