### ISSUE TITLE
possible to exclude conmem?

### ISSUE THREAD

**Issue by hliang** [bcbio/bcbio-nextgen#2675]
For parallel execution on slurm, bcbio uses `-r conmem=4` by default, even when the option is not specified in bcbio_nextgen.py command. The auto-generated controller job script (SLURM_controllerABunchOfNumbers) has a parameter like `#SBATCH --mem=4000`.

For some reason, the cluster we are using doesn't like `--mem`, and the scheduler will not accept jobs with that parameter. Is it possible to exclude `conmem`, so the job script won't have the `--mem` parameter? @roryk 

Thanks,

-liang

**Comment by roryk** [comment]
Hi Liang,

Thanks, sorry for the problem. That is a weird policy.

We have that set because by default lots of folks have their scheduler to have an unreasonably low default memory set. Unfortunately, `--mem` will be necessary for most of the jobs that bcbio spawns, so fixing it just for the controller won't help much since all of the engine jobs won't work as well. It would be a good idea to talk to the admins and ask why `--mem` is disabled; that is a pretty important parameters to be setting for running jobs, otherwise we can't control the amount of memory used. Let me know what they say, I'm curious to hear the reason why. We might be able to work around it if there is a parameter that is similar to what `--mem` does that they do allow.

**Comment by hliang** [comment]
Thanks Rory.

I manually edited cluster_helper/cluster.py, so the resulting controller and engine jobs have disabled parameter ( commented out `#SBATCH --mem=`).

Unfortunately, after this worked around, we faced another issue. The cluster only allows job submission from login nodes... Since we are submitting the bcbio_nextgen.py task as a job, it will run on a compute node, and the controller job submission will fail.

Do you know if there is a workaround for such restriction?

-Liang

**Comment by roryk** [comment]
Hi Liang,

The main bcbio job does not do very much processing, so you theoretically could run it on the login node and it will submit all of the jobs from the login node, but that isn't a super good solution since you're doing something you're not supposed to be doing from the login node.

You could try that and see if it works, but I'm guessing that you are going to run into other problems because `--mem` isn't respected.

**Comment by hliang** [comment]
Roryk,

Just tried starting bcbio on login node. And realized the cluster had disabled array jobs... (talking about stampede2 in TACC). They provide an alternative, but not something standard. Not sure if it's easy/worth to include in cluster_helper.

I might have to run bcbio in local mode, on one compute node, to handle small dataset.

Thanks for the discussion. Feel free to close this issue.

**Comment by roryk** [comment]
Hi Liang,

Sorry that bcbio doesn't cover this case-- cluster_helper covers a lot of different setups but supporting this one would be hard. On the upside, it looks like stampede2 has some pretty nice machines with a good amount of cores on them so hopefully a local run will get your work done in a reasonable amount of time. Thanks for following up!
