### ISSUE TITLE
Updation of dbnsfp to version 4.0

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2682]
Hi, I noticed that the dbnsfp version has been updated to 4.0, but bcbio has not updated. Could you make a update for this database?

**Comment by chapmanb** [comment]
Thanks for the suggestion. Because of the size and complexity of working with dbNSFP, we've been trying to limit updates to when it introduces important new features that people aren't getting with other sources. Out of curiosity, what 4.0 changes were you hoping to get with an update? Thanks for starting this discussion.

**Comment by hliu2016** [comment]
@chapmanb 
Thanks for your prompt reply. I just noticed that dbNSFP's latest version is 4.0. I have not dig into the new features brought by this updation.

**Comment by matthdsm** [comment]
Hi Brad,

I've been keeping an eye on this. dbNSFP4 is still in Beta, so I'd advise against updating immediately. I would however, look at updating when the final release is ready. 
v4 updates a lot of existing prediction scores, and adds quite a few new ones.

As I said, I'm keeping an eye on this and will push the required updates once the final version is available.

Cheers
M

**Comment by roryk** [comment]
Looks like we pressed pause on this for now, please open up a new issue if there's enough of a change that we should update it.

**Comment by naumenko-sa** [comment]
Hello!

Finally, I've updated it - dbnsfp3.5a had issues with downloading (gdrive responded - sorry, too many downloads), 
ftp server did not have 3.5a ftp://dbnsfp.softgenetics.com/. So, I've updated recipes to 4.1a. 28G instead of 16G.

Re-opening for some time - let us know if there are any issues.

Sergey
