### ISSUE TITLE
Conda getting stuck at "solving environment" when running: bcbio_nextgen.py upgrade -u development --tooldir=/path/to/bcbio_nextgen/tools --data --tools --cwl

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2713]
Hi, 

Conda is getting stuck at "solving environment" when running:

```
bcbio_nextgen.py upgrade -u development --tooldir=/path/to/bcbio_nextgen/tools --data --tools --cwl
```

There was no progress after several hours of waiting. 

I also tried creating a fresh install, then trying to upgrade, and after leaving it overnight for more than 8 hours, conda was still stuck at "solving environment". This happened two times in a row, each time with a fresh bcbio install, so the problem appears to be reproducible.

Running with `upgrade -u stable` and `--cwl` works fine for a fresh bcbio install. However, running with `upgrade -u development` after that results, again, in conda "solving environment" forever.

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. This is likely due to the recent update to use R 3.5.1, so conda is resolving all the package changes. We've been trying to work on more general fixes for this (you can see the discussion in bioconda/bioconda-recipes#13774 for all the details) but right now don't have a practical workaround. The two things to do are:

- Wait for it to resolve.
- Remove your conda environment and run bcbio_nextgen_install.py against the same data directory and let it reinstall.

We're going to have one more bigger change to use Python 3.7 and then hopefully we won't have so much package turnover and avoid this on most updates. Sorry again about the issue and hope this helps.

**Comment by amizeranschi** [comment]
Thanks a lot for the link. It was interesting to read about the trouble with R packages in conda.

I've never realized that the `bcbio_nextgen_install.py` script also accepts the option `-u development`. I made a new fresh install using this option and then attempted to install CWL support with:

```
bcbio_nextgen.py upgrade -u development --tooldir=/path/to/bcbio_nextgen/tools --data --tools --cwl
```

However, this got stuck again at `Solving environment: ...working...`. 

I'll let it run for a while with the hope that it will eventually make it through.

**Comment by amizeranschi** [comment]
After a couple of HTTP timeout errors and subsequent retries, the upgrade finished successfully. Thanks for your help.

**Comment by chapmanb** [comment]
Glad this finished successfully for you. We've been working on it as well and believe the longer runtimes are due to the transition to a new openssl version, which requires a lot of package upgrades. I added a pin to the recent version during install which helps speed up the solving time for me when upgrading. Hopefully this will help improve the situation for any future installs.

**Comment by amizeranschi** [comment]
Thanks a lot for dealing with this. I've done another upgrade as well and it looks like pinning the openssl package version has really sped things up.
