### ISSUE TITLE
Configuration check should not allow for duplicated "description" items

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2738]
I found out the hard way by mistakenly putting a number of samples with the same name: it caused many different files to be aligned with the same name, at least with the `smallrnaseq` pipeline, and of course all transaction checks screamed in my face.

**Comment by chapmanb** [comment]
Luca;
Sorry about the issues. The current YAML lint checks should identify this as an issue prior to running:
```
ValueError: Duplicate 'description' found in input sample configuration.
Required to be unique for a project: ['Test1']
Problem found in these samples: ['Test1', 'Test1']
```
Would you be able to post the problematic configuration so we can identify how it manages to get around these checks? Thanks much.

**Comment by lpantano** [comment]
Hi,

could it be that you did the -w template command, and then you lost some
samples, and then you added later and re-started?

It happened to me that I lost the sample because the naming and re-starting
was the real issue. Not sure if you got the issue from the very beginning.

There is a bug when adding samples after alignment is done that is messing
with the BAM files.

Brad, do you know if we check when running the -w template whether there
are samples with same names that we lose in the final yaml file?

**Comment by lbeltrame** [comment]
I already "fixed" it, but IIRC I had distinct `samplename` in the template, but identical `description`. Each of the duplicated `description` entry pointed to a different FASTA file. This caused all sorts of funny races during the run (`smallrnaseq` for the record).

**Comment by chapmanb** [comment]
Luca and Lorena;
Thanks for the details. We don't check currently for duplicates as part of the templating so this could definitely use some attention if we wanted to try and catch it there. Luca, I'm confused how you were able to kick off the actual run since bcbio should have complained about having duplicates. If you're able to provide an example of the configuration that caused the issues this could help in trying to isolate how best to fix beyond the templating improvements Lorena suggested.

**Comment by roryk** [comment]
Hi Luca, I couldn't make this problem happen for the reasons Brad stated above-- do you have an example of the configuration that was running into this problem so I can look at it?
