### ISSUE TITLE
Does ensemble vcf tend to keep variants from gatk4 over others?

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2748]
Hello,

I have often observed that when there are multiple variants called by GATK4 and one phased variant for those variants called by vardict,  ensemble vcf tends to keep the multiple variants.  For example,  GATK4 calls following variants. 
RUNX1    c.202delG    p.A68Pfs*4
RUNX1    c.195_201delTGCCCTGinsA    p.L67_A68del
RUNX1    c.200T>A    p.L67Q
RUNX1    c.190_198delGGCGCTGCC    p.G64_A66del
RUNX1    c.190_193delGGCG    p.G64Lfs*7

And vardict calls these as one variant
RUNX1    c.190_201delGGCGCTGCCCTGinsCA    p.G64Qfs*5

I wonder if there is any way that the preference can be given to a phased variant?

Many thanks!

**Comment by dauss75** [comment]
I should have provided more accurate info and a proper question.

In my yaml file,
    ensemble:
      numpass: 1
    variantcaller: [gatk-haplotype, vardict]

I understand that ensemble vcf takes union of thses callers. When gatk and vardict reports a variant with same genomic positions, I wonder how a priority is given among the two.

**Comment by chapmanb** [comment]
Thanks for the question. In ensemble calling, the outputs are taken with preference to the order specified in `variantcaller`. So in your run, `gatk-haplotype` is first if present, otherwise `vardict` calls. If you prefer VarDict you can swap these to preferentially get those. We don't have any other more complicated logic for phasing or anything else beyond the order of preference. Hope this helps.
