### ISSUE TITLE
TypeError at the end of running bcbio_setup_genome

### ISSUE THREAD

**Issue by eyalbenda** [bcbio/bcbio-nextgen#2802]
Don't know if it's python3 related, but I got the following error at the end of building a custom genome with 1.1.5.

`Updating Galaxy .loc files.
Traceback (most recent call last):
  File "/home/ebendavid/bcbio/tool/bin/bcbio_setup_genome.py", line 354, in <module>
    loc.update_loc_file(galaxy_base, index, args.build, index_file)
  File "/home/ebendavid/bcbio/anaconda/lib/python3.6/site-packages/bcbio/galaxy/loc.py", line 64, in update_loc_file
    ref_loc = os.path.abspath(ref_loc)
  File "/home/ebendavid/bcbio/anaconda/lib/python3.6/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. This is due to the output of one of the reference index functions being `None`, so it's not a python 3 specific issue. If you're able to help debug to provide other information adding a `print(indexed)` debug statement here:

https://github.com/bcbio/bcbio-nextgen/blob/5f903ad17f991f115c2c0914b267ef25f19103a6/scripts/bcbio_setup_genome.py#L303

would help identify which index method returns None. It would also help to see the command line you ran which might give pointers as well. Thanks much for the help debugging.

**Comment by eyalbenda** [comment]
So the indexed vector has "'hisat2': None". Removing hisat2 from the list of indices solves the problem. I don't really need hisat2 so that's fine.

**Comment by chapmanb** [comment]
Thanks much for following up on this. Glad the workaround fixed it for you, and we also pushed a fix to avoid the error in the future if this happens.
