### ISSUE TITLE
Set up a custom genome with already made index

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#2807]
Hi all,
 I would like to install a custom genome using `bcbio_setup_genome.py`

As stated in the documentation, this will create index for all aligners. However I have already computed the index, so I am wondering if it is possible to install this new genome skipping the creation of the index.

Thanks,
Laura

**Comment by chapmanb** [comment]
Laura;
We don't have an automated way to incorporate pre-existing indexes. If your index is already in the form that bcbio expects you could place it into the organized genome folder alongside the other indexes and it will hopefully recognize this and skip it during the preparation process. We haven't tried to work a lot on this case as it's typically a lot of manual steps and hard to automate, and it's practically easier to just do some extra computational work rather than spending time trying to get things in the right form. Hope this helps.

**Comment by LMannarino** [comment]
Hi Brad,
thanks for your answer. It sounds good, I'll try.

Best,
Laura
