### ISSUE TITLE
Invalid cross-device link - hard link between two filesystems

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#2827]
Hi,

I am running a `variant2` analysis on our cluster. I was trying to write temporary files to the `/scratch` volume (`/scratch/bcbio`), but `bcbio_nextgen.py` returned the following error:

```
OSError: [Errno 18] Invalid cross-device link: '/scratch/tmp_bcbio/tmp_1yvm79e/FILENAME.fastq.gz' -> 'PROJECT_DIRECTORY/FILENAME.fastq.gz'
```

The temp directory files and the original files are located on two different filesystems, and `bcbio_nextgen.py` seems to be trying to make a hard link between the two. Is this a known issue? Would it be possible to use symbolic links?

Thanks a lot for looking into this.

**Comment by roryk** [comment]
We will need more information to debug the issue, could you post more of the traceback?

I suspect you are running into this: https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link

Could you set your temporary directory to something on the same filesystem?

**Comment by FedericoComoglio** [comment]
Hi @roryk - thanks a lot for your reply. This error occurs at the very beginning, running with `-n 1` to debug only results in a few lines in the log, with the error occurring after 

```
gunzip -c PROJECT_DIRECTORY/FILENAME.fastq.gz | /mnt/data/galaxy/../anaconda/bin/bgzip --threads 6 -c /dev/stdin > /scratch/tmp08rhus9m/FILENAME.fastq.gz
```

Setting a temporary directory on another location on the same filesystem works - this is the solution I used so far. However, because our cluster has a large attached local storage, it would be convenient to write temporary files to `/scratch`.

Thank you!

**Comment by roryk** [comment]
Hi FedericoComoglio,

I think we're probably not going to fix this one, since we can't guarantee third party tools also aren't writing to temporary disk in this way and there is already a workaround and python's workaround is to just copy the files, so it isn't actually using the temporary space as temporary space. We're also going to have to fix every single time we touch the temporary directories in the code, so it is going to be a long process of finding all of the places we do this. If you can provide more of the log so I can see what line of the code is doing this it would be helpful for me to see what it would take to work around it, but I'm not likely to fix this.
