### ISSUE TITLE
Skipping vcfanno configuration: somatic. Not all input files found.

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#2864]
Hi Brad et al, 

> Skipping vcfanno configuration: somatic. Not all input files found.

I get this message when I start a run, regardless if its tumor-only or not. I just wanted to check what I am missing for from my install to use the somatic config ? 

below is my install command for bcbio, 

> python bcbio_nextgen_install.py /shared/pipeline-user/bcbio --tooldir=/shared/pipeline-user/tools/local --genomes hg38 --aligners bwa --datatarget variation --datatarget gemini 

Thanks again for a great tool!

**Comment by roryk** [comment]
Hi Warren,

Sorry about that, we can't include the COSMIC annotations automatically with bcbio for hg38 due to licensing restrictions. https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#customizing-data-installation has a section if you scroll down that will show you how to manually install them. That error message is pretty uninformative, I'll fix it so it is more specific. Hope that helps! Feel free to reopen if you run into any problems after manually installing COSMIC for hg38.

**Comment by waemm** [comment]
Thanks @roryk for the fast response! Ok, so this is just because COSMIC is not installed? Just to double check, this routine just annotates the VCF file with "SOMATIC"? Is it possible to run this without using COSMIC ?

**Comment by roryk** [comment]
Yup, you got it right. You can run it, you'll just be missing the COSMIC annotations of known somatic variants.

**Comment by waemm** [comment]
Thanks @roryk, how do I get this to run without COSMIC then? Do I just need to create two empty cosmic files in the variation folder? Is there another flag I need to set somewhere or download I need ?

ie.
> cosmic.vcf.gz  

> cosmic.vcf.gz.tbi

**Comment by roryk** [comment]
Hi Warren,

The annotation of the VCF file with the somatic variants from COSMIC needs COSMIC to be installed, it won't do anything if you don't have COSMIC installed. This is just a warning so you can ignore it if you don't care about those annotations.
