### ISSUE TITLE
Too many files open error while running multiple bcbio instances

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#2870]
Hi Guys,

We're currently having quite a difficult time processing some large exome files, they are 50-70GB per mate fastq file so ~ 100GB+ per fastq file pair.

We are encountering problems that I guess are largely due to limits on the hardware infrastructure ( we're running this on AWS) where initially having 10+ jobs trying to load data from the shared mount proved very slow. To get around this we created smaller batches of samples to try stagger the use of IO by letting the first batch complete alignment prep/alignment and merging  before running a second. This however has resulted in other errors with " too many files open" ( see the example attached). I have read the section in bcbio about this, I understand that bcbio sets the ulimit of its controller and engines, I have also modified the sge platform as directed but still seem to be getting the error.

I have two questions, are these errors coming from the multiple instances of bcbio_nextgen.py  which I am running on the masternode ? I would assume these processes are only submitting jobs to be run on the cluster nodes? Nonetheless I have upped my ulimit on the head node to try prevent this. 

Secondly, in your experience is there a better way to deal with this? Is it better to just analyse all the data together with fewer active nodes to limit IO ? I don't know if there is an option to have all these IO procedures happen locally on each cluster nodes local drive?

Thanks!

[error_ulimit.txt](https://github.com/bcbio/bcbio-nextgen/files/3350179/error_ulimit.txt)

**Comment by chapmanb** [comment]
Warren;
Thanks for the detailed error report and apologies about the issues. To start with your questions:

- The error looks to be coming from the worker node (ip-172-34-10-52) when running GATK's Spark BQSR. If you're using SGE to submit jobs and this runs through that, bcbio should be trying to give you 10240 file handles (https://github.com/roryk/ipython-cluster-helper/blob/1db885e831654fa6ad5d20be7a35788852d95e85/cluster_helper/cluster.py#L118), so either GATK is really having issues with tons of file handles here or something else is going on. There is a GATK issue mentioning this (https://github.com/broadinstitute/gatk/issues/5316) that it seems like should be fixed in the version you're using.

- If you're using AWS instances with large attached disk you can use that for processing rather than a shared filesystem. If you mount the local disk consistently, then add it as the temporary directory (https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#temporary-directory) and that should take load off the shared filesystem.

It's not clear to me that if you remove the filesystem bottleneck it'll resolve the large number of file open issue as these seem separate. If you can provide more details on where the open file system errors originate and how the jobs get sent there that might help provide more specific advice, but hope this is useful.

**Comment by waemm** [comment]
Thanks Brad, I will definitely try adding large local temp storage. I am also considering switching to the storage-optimised nodes on AWS as it seems storage access and speed might be the largest bottleneck we have. If you have any tips for running bcbio on AWS infrastructure with large files please do let me know.
