### ISSUE TITLE
Deepvariant integration

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#2911]
Hi! Do you think about integrating deepvariant?

**Comment by roryk** [comment]
Hi @kokyriakidis,

Brad did a bunch of work comparing DeepVariant to the other callers here: https://github.com/bcbio/bcbio_validations/tree/master/deepvariant

and it is integrated in bcbio, but isn't documented. I think the ultimate conclusion was that the other callers did about just as well, but we haven't tested it since v0.6 and v0.8 is out so that conclusion might no longer hold. @chapmanb does that sound about right?

**Comment by kokyriakidis** [comment]
V0.8 is a major improvement. I would be nice compare it again with the
current version :)

Στις Πέμ, 22 Αυγ 2019 στις 11:37 μμ ο χρήστης Rory Kirchner <
notifications@github.com> έγραψε:

**Comment by chapmanb** [comment]
Thanks for this discussion. DeepVariant will work within bcbio and the main reason for lack of documentation is that the DeepVariant conda binary is pre-built so won't run on all of the platforms we support. We've worked hard to try and build from scratch to port to additional platforms but haven't been able to get that all working with the build dependencies. You should just be able to add `variantcaller: deepvariant` to your configuration and have it run. Please let us know if you run into any issues.

**Comment by kokyriakidis** [comment]
Thanks for the info! Does deepvariant in Bcbio use 0.8 model?

**Comment by chapmanb** [comment]
Yes, it'll include the latest release from bioconda (https://anaconda.org/bioconda/deepvariant) which is the 0.8 release. It'll be installed in the `dv` conda environment as part of the install. Hope this helps.

**Comment by roryk** [comment]
Thanks Brad! Let us know how deepvariant works for you Konstantinos!
