### ISSUE TITLE
NeuSomatic as a tumor-normal variant caller

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#2926]
Have a look at NeuSomatic. It this papers it seems that it outperforms every other method, including the ensemble one using the best known tools out there (Mutect2, Strelka2 etc)

https://www.nature.com/articles/s41467-019-09027-x

**Comment by roryk** [comment]
Hi Konstantinos,

Thanks-- I'd take the claim that it outperforms the other methods with a huge grain of salt, since they ran the other methods using the default parameters, not sure how that comparison got past reviewers. We're happy to investigate support if there are some more fair metrics showing it is doing better than the other callers, but I think that paper isn't support for it.

**Comment by roryk** [comment]
Feel free to reopen if you find some better comparisons or run a comparison on your own and show it is doing better. We're always looking to improve, but have to focus our limited resources on things that we have strong evidence for being a better way to go. Thanks again!
