### ISSUE TITLE
VCF output format

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#2929]
Hi! Can I somehow format the VCF output so it contains all positions, even if they are 0/0 (reference) or ./. (missing)? I know that missing positions can be added using the GATK 'EMIT_ALL_SITES' but I am not sure if it causes a pipeline problem

**Comment by roryk** [comment]
Hi Konstantinos,

We don't have an option to do this, what's your use case for doing that?

**Comment by kokyriakidis** [comment]
I want to use the PharmCAT software from PharmGKB which has some requirements regarding the VCF format:

https://github.com/PharmGKB/PharmCAT/wiki/Preparing-VCF-Files

**Comment by roryk** [comment]
Gotcha-- that won't get you all the way there unfortunately. They have an interval file they are using to limit it to the regions they need:
https://github.com/PharmGKB/PharmCAT/wiki/pgx.interval.file.list  Their workflow seems pretty specific for the tool, and they need the variants reformatted in specific ways as well.

Their interval list is pretty small, so variant calling should be pretty fast since it is calling in only a small number of regions. I think what I'd do here is take the alignments from bcbio use that as a starting point for their tool if I wanted to use bcbio at all.

**Comment by kokyriakidis** [comment]
I just wanted to the ensemble method to achieve higher precision and sensitivity. Thanks for your suggestions!

**Comment by matthdsm** [comment]
hi @kokyriakidis 
Maybe this helps!
https://github.com/bcbio/bcbio-nextgen/issues/2837

Cheers
M

**Comment by kokyriakidis** [comment]
Hi! If I use an additional option in GATK and use the ensemble method, will it keep the 0/0 or ./. In the final vcf?

**Comment by matthdsm** [comment]
Using ensemble calling will nullify the effect of the extra GATK param as this is essentialy majority calling, so all calls from gatk (including the HOM REF) will be filtered out. You're best of using only GATK IMO.

M

**Comment by roryk** [comment]
Thanks Matthias and Konstantinos for the discussion!
