### ISSUE TITLE
Metrics shown only for most recently run case

### ISSUE THREAD

**Issue by sxv** [bcbio/bcbio-nextgen#2934]
If I run multiple cases / samples with the same fc_date and fc_name, the resulting upload directory contains all of my variant call VCFs, appropriately named (which is good), but the other QC and log files are overwritten by the most recently run case:

```bcbio-nextgen-commands.log
bcbio-nextgen.log
data_versions.csv
metadata.csv
multiqc
programs.txt
project-summary.yaml
```

Therefore I am unable to view multiqc results, for example, except for the most recent case. Is this desired behavior? Am I supposed to be giving each case a unique "fc_name" to avoid this? thanks.

**Comment by chapmanb** [comment]
Sorry about the confusing results here for your runs. This is the intended behavior since `fc_date` and `fc_name` are meant to uniquely categorize a single analysis run. From bcbio's perspective a run with these identical to a previous run is replacing the old analysis. You'd want to provide unique names for unique analyses to avoid this. Hope this helps.

**Comment by sxv** [comment]
Thanks, I'll start using unique names from now on. In this case, do you have a recommendation for running multiqc on the completed runs? I'm mostly interested in alignment and coverage reports.
