### ISSUE TITLE
Heads-up: VEP annotations can have a SOMATIC field and this breaks vcf2db parsing

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2966]
As the topic says, the way vcf2db parses annotations (https://github.com/quinlan-lab/vcf2db/issues/61) can break in case VEP includes a SOMATIC field, because it will overwrite the SOMATIC flag already present when vcf2db parses the file, and will cause a cryptic constraints error when trying to build a database.

**Comment by chapmanb** [comment]
Luca;
Thanks much for the heads up on the issue. In this case, it seems like VEP should not be overwriting or changing the existing SOMATIC flag. That's pretty widely used across callers. Is it possible to raise an issue with the VEP team and see if they have a workaround for this issue we could apply in bcbio to avoid the problem? Thanks again for looking into this.

**Comment by lbeltrame** [comment]
I see the issue as twofold:

- VEP has an additional SOMATIC field, but, AFAICS, it is part of the `CSQ` field in INFO;
- When vcf2db parses the info, it overwrites the somatic field because `geneimpacts` misparses the record (as far as I could remember when I investigated the issue)

How can one report bugs to the VEP? Even if it is a problem with vcf2db, the naming clash is unfortunate.

**Comment by chapmanb** [comment]
Luca -- thanks for the additional details. It sounds from your description like geneimpacts/vcf2db is probably the right place to fix this, rather than VEP since it's putting it into the CSQ field. Apologies, I'd misunderstood. It doesn't seem like there is much we can do on the bcbio side to mitigate the problem but hopefully it'll get fixed from the gemini side soon. Thanks again for digging into it.
