### ISSUE TITLE
ChIP-Seq pipeline bowtie as aligner

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#2974]
Hi,
 in ChIP-Seq pipeline the aligner choices are: Bowtie2 or bwa mem. However, can I suggest to add Bowtie (the first version)? 
Bowtie2 allows for gapped alignment and is faster for long reads, however sometimes the use of Bowtie is preferred which is useful for ungapped alignment. 

Thanks,
Laura

**Comment by roryk** [comment]
Hi Laura,

We looked at bowtie1 vs bowtie2 when we first put the pipeline together, and it didn't matter very much. I think people use bowtie1 because there are options to only output a single alignment, but we handle that downstream instead. So we're probably not going to implement bowtie1 support unless it turns out there is a really strong reason to. Thank you for the suggestion though!
