### ISSUE TITLE
Could I pass --panel-of-normals parameter to Mutect2 ?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2976]
I think the --panel-of-normals parameter is very helpful to remove artificial variants. Is there any method to pass this parameter to Mutect2 from bcbio?

**Comment by chapmanb** [comment]
You can using the general configuration parameter for passing panel of normals:
```
background:
  variant: /path/to/your/pon.vcf.gz
```
More details here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#variant-calling

Hope this works for you.

**Comment by hliu2016** [comment]
@chapmanb 
Hi Brad, does this configuration parameter support tumor-only call of Mutect2 in bcbio? I know that Mutect2 does supoort the --panel-of-normals option in tumor-only mode.

**Comment by hliu2016** [comment]
@chapmanb 
I have tested this configuration, and this parameter caused error in Muetect2 running. 
My yaml file is as below:

> details:
>   - analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       trim_reads: atropos
>       adapters: [truseq2, polya, illumina]
>       variantcaller: [mutect2]
>       background:
>         variant: /ngs/zhengu/config/pon.vcf.gz
>       variant_regions: /ngs/zhengu/config/3214551_Covered.bed
>       mark_duplicates: false
>       recalibrate: false
>       realign: false
>       effects: snpeff
>       remove_lcr: true
>       min_allele_fraction: 1


I run the pipeline twice and got the same error. The log is attached. Could you take a look at this problem?
[log.txt](https://github.com/bcbio/bcbio-nextgen/files/3737900/log.txt)

**Comment by chapmanb** [comment]
Thanks for testing this out. Using a panel of normals in tumor only samples should work and it looks like you're running into a different issue with the `-ploidy` setting. This got removed in GATK 4.1.1.0 and should have been fixed in bcbio as of version 1.1.5: https://github.com/bcbio/bcbio-nextgen/commit/ecd736a3beb0dcd6d0d2c1487acc49306d412d53#diff-6f6ad3f18c41a275b41c7bdf6a819e5b. Is it possible you're running an older version than that? If so, you could either upgrade bcbio or downgrade gatk to an older version. Hope this helps.

**Comment by naumenko-sa** [comment]
please re-open if it is still an issue
