### ISSUE TITLE
question: improving joint GT for trio's

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#3016]
Hi,

Currently our production pipeline uses the bcbio "batch" to differentiate between trio's on a single flowcell. We use GATK for variant calling up to gvcf, and then do joint genotyping per batch.
However, this is less than ideal since the batch sizes are small (3 individuals). We were thinking to improve on this by joint genotyping all samples on a single flowcell, and differentiating the trio's later on.

My question is:
- What's the best way to differentiate between families (trio's) within the batch (e.g. the flowcell)?
Do I use a giant PED file with all data or do I add a ped file per trio and associate the small ped with the correct samples in the config? How will the affect the resulting gemini db?
- Alternatively, is there a way to make bcbio joint genotype the entire run and then split the resulting vcf per trio?

Thanks
Matthias

**Comment by roryk** [comment]
Hi Matthias,

Good question. Samples in the same batch will all get called together, so you could do them all in the same batch and then provide a PED file which describes the family structure. This is good if you are going to be comparing across families, since it will ensure all locations where there is a variant in any sample has calls for every sample.

Joint genotyping is only really useful if you have on the order of thousands of samples, otherwise just calling them all in the same batch should work fine.

There isn't a way to break up the VCF into trios in bcbio at the end, but you should just be able to keep the one big file and subset it however you like. We use GEMINI to do those types of more complex queries.

**Comment by matthdsm** [comment]
Thanks for the info!
I noticed vcf2db support bigger db's too? Can we somehow modify the behaviour of bcbio to incrementally push new data to a postgres instance instead of sqlite?

Thanks
M

**Comment by roryk** [comment]
Hi Matthias,

bcbio uses `vcf2db` to load the GEMINI database, yup. Incrementally updating the database doesn't work well because the new samples added need to have the variants called all at the same spots as the old samples, so you need to re-call and create a squared off VCF file anyway.

**Comment by matthdsm** [comment]
Thanks for the info!
Cheers
M
