### ISSUE TITLE
aws batch 

### ISSUE THREAD

**Issue by maxabruzzi** [bcbio/bcbio-nextgen#3022]
Dear developers,

This is an actually an inquiry. Is there an estimation on when the support for "AWS Batch and Cromwell" can be brought up? Thanks!

Max

**Comment by mjsteinbaugh** [comment]
I'm running some NGS scripts on AWS Batch using Nextflow but would also be interesting in helping update bcbio to support Batch and/or AWS Lambda.

**Comment by matthdsm** [comment]
Hi,

As far as I know those are already supported. Bcbio can generate CWL which can then be run by virtually any CWL compatible jobrunner. So if your CWL interpreter supports AWS Batch or whatever, you can run the generated CWL, barring some configuration tweaks.

Personally, I've already run several bcbio analysis using CWL and cromwell, and this seems to work just fine. You just have to edit the cromwell config to use the correct back end.

Cheers
M

**Comment by chapmanb** [comment]
Max and all;
Thanks for the question and interest. As Matthias mentioned, we have moved to supporting AWS, GCP and Azure by using external CWL runners. Cromwell is the best target for AWS batch support and they've had some recent improvements since the last time we tested. It will likely need further development, which would mean a dedicated person with interest trying out the existing support, finding and narrowing any errors, and reporting back to the Cromwell team so they can provide suggestions or fixes. The documentation on current status is here for anyone that has time and expertise to pick it up: https://bcbio-nextgen.readthedocs.io/en/latest/contents/cloud.html#amazon-web-services-aws-batch Sorry to not have this working out of the box but hope this helps for context.
