### ISSUE TITLE
RNA-Seq MultiQC % duplicates discrepancy

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#3029]
Hi,
I've run RNA-Seq pipeline and looking at the final MultiQC report. I would like to known how the column "Dup" meaning "% Duplicated reads" from bcbio group is calculated, since I saw a very high difference between this value and the value calculated with FASTQC on raw-data. 
I can make an example on 3 samples I have: FASTQC on .fastq (independent from bcbio-nextgen) gives me a very high % of dup, around 75%, 80% and 76%. MultiQC (bcbio pipeline) results on the same samples after alignment gives 19%, 14% and 20%. How this values could be so different? This seems very important in order to choose whether or not analyze these samples.

Thanks,
Laura

**Comment by roryk** [comment]
Hi Laura,

Duplication is a pretty useless metric for RNA-sequencing data, so I would just ignore it. You can see duplication rates of 300% via the FastQC metric on libraries that are perfectly fine. The FastQC duplication calculation is different from the one that is calculated from markduplicates, so that is where the difference lies. https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/8%20Duplicate%20Sequences.html has a description of the duplication metrics in FastQC, you can see they say to basically ignore it for RNA-seq data. Hope that helps some!

**Comment by LMannarino** [comment]
Hi Rory,
 very helpful. Many thanks!

Laura
