### ISSUE TITLE
Move utility scripts to a separate repo

### ISSUE THREAD

**Issue by hackdna** [bcbio/bcbio-nextgen#3105]
Some of the utility scripts are not a core part of bcbio but may have dependencies that are difficult to install due to conflicts with the core dependencies:
* https://github.com/bcbio/bcbio-nextgen/tree/v1.2.0/scripts/utils
* https://github.com/chapmanb/cloudbiolinux/pull/339#issuecomment-589708378

If these scripts are moved to a separate repo (e.g., bcbio-utils) then they could be combined into a PyPI package for easy installation along with their dependencies.

* [x] move files to the new repo
* [x] make sure all scripts can run and add all dependencies to `environment.yml` in bcbio-utils
* [x] add description of each script to `README.md` in bcbio-utils

**Comment by roryk** [comment]
Thanks, Ilya-- I added you to the bcbio group so you should be able to make a new repository under the group.

**Comment by hackdna** [comment]
Thanks for adding me to the org :) Do you have a preference for a name of the new repo? Some examples: bcbio-utils, bcbio-scripts, bcbio-tools.

**Comment by roryk** [comment]
Great-- whatever makes sense, bcbio-utils sounds good to me.

**Comment by matthdsm** [comment]
On the same note,
shouldn't cloudbiolinux also be moved under the bcbio organisation since it's directly linked to the dependencies and resources for bcbio?

Cheers
M

**Comment by hackdna** [comment]
Simply adding the [Conda package YAML file](https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml) to the bcbio-nextgen repo would work too.

**Comment by naumenko-sa** [comment]
Thanks for these suggestions!

**Ilya**:
Besides being a conda yaml provider, 
cloudbiolinux is a collection of many data installation recipes:
https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes

Having it as a separate entity is very useful to debug recipes in the first place.

**Matthias**:
I think historically cloudbiolinux's scope was much wider than just being a component of bcbio installer. And it still holds this potential - Brad or somebody else might develop it further. Some users don't run bcbio pipelines, they just need to maintain their installation of conda packages + data files for the lab.  Moving cloudbiolinux under bcbio won't solve any issues, but may disrupt installation/updates for some users (i.e. we may create some minor issues this way). So I'd propose to leave it for now as is, since we have a lot of more pressing issues, even ones related to cloudbiolinux: R3.6, python environments, miRNA for Drosophila etc.

**Comment by hackdna** [comment]
Thanks Sergey. Curious, how does having the data installation recipes in a separate project help with debugging?

**Comment by hackdna** [comment]
Moving is complete: https://github.com/bcbio/bcbio-utils
