### ISSUE TITLE
Control-FREEC as a CNV caller

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3106]
Control-FREEC has been praised by the bioinformatics community and it takes into consideration all forms of bias I can think. I was wondering if we could have an integration of the tool in Bcbio.

https://github.com/BoevaLab/FREEC

**Comment by naumenko-sa** [comment]
Hi Konstantinos @kokyriakidis!

Thanks for this suggestion!

You are very welcome to contribute to bcbio! 
And we are interested to further improve SV/CNV detection.
The potential roadmap for this use case might be:

1. Evaluate the tool, clarify its use case, prove that it worth investing time to incorporate it and support it in the future.
- [ ] A recent review shows top tools for (germline) WGS SV/CNV detection: 
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1720-5
The conclusion was that out of 69 tools manta is a safe choice for DEL and INS. control-FREEC achived very modest results (see fig1a,b). We already support manta and wham, also we support duphold which annotates SV events detected by split-reads with read depth. So for this use case we would just recommend using manta or combination of manta/lumpy/delly/wham/cnvkit calls. 
- [ ] The review says: "AS-GENESENG, Control-FREEC, OncoSNP-Seq, and GenomeSTRiP **may** more accurately detect SVs in other types of applications, such as somatic SV detection or SV calling with whole exome sequencing data or multiple sample data because these algorithms have been more intensively designed for such applications." So the potential niche for control-FREEC might be somatic (cancer) SV detection. Currently, we would suggest running manta, seq2c, cnvkit in bcbio and consider all calls. If you could expand that **may**, run validations and show that control-FREEC outperforms manta, seq2c, cnvkit, and 3 other competitors mentioned in the article, that would be a great contribution and that would improve control-FREEC priority among other issues/improvements in bcbio.
2. Implementation
- [ ] learn how to run control-FREEC in detail and create a propotype runner script
- [ ] publish validations in https://github.com/bcbio/bcbio_validations/
- [ ] push control-FREEC to bioconda
- [ ] make sure its installed in cloudbiolinux
- [ ] write a wrapper in `bcbio/structural`
- [ ] make sure wrapper is called in variant2 pipeline
- [ ] make sure results are saved in `final` in the end of the run
- [ ] prepare a small test and add it to the `test` directory
- [ ] document how to use control-FREEC in the bcbio docs.

Sergey

**Comment by naumenko-sa** [comment]
please feel free to reopen if there are any updates.

**Comment by hackdna** [comment]
Would it be useful to keep this issue open in case someone else would like to work on this?

**Comment by naumenko-sa** [comment]
We are trying to reduce the amount of open issues to focus on what we are actually working right now by closing stalled issues, where nothing is happening, the issue is not critical, and we don't have time to work on it. This way we indicate to the community what we are really pushing. The issue remains open for 1-2-3 month for everybody to chime in.

Ideally, it should not be more than 10-20 open issues - a manageable size for the team.

The priority is on blocking issues, which break up the basic functionality described in user stories, validations, necessary updates. This issue is an example of 'please introduce a new tool' issue. Sometimes it is easy, in most cases it is not.  In that particular case it needs a lot of work outlined above. 

Given that we currently are having blocking issues with gatk in RNA-seq, CNVkit, deepvariant etc, we just can't chase this one.

If somebody wants to contribute, please comment and for sure we will reopen any closed issue.
