### ISSUE TITLE
Integrate additional GiaB samples (NA24694 / NA24695)

### ISSUE THREAD

**Issue by sam-ber** [bcbio/bcbio-nextgen#3121]
I apologize in advance if this is not the correct place, I already asked in the [cloudbiolinux repo](https://github.com/chapmanb/cloudbiolinux/issues/334) to also include NA24694 and NA24695 as references to the standard bcbio installation.
This would complete the set of GiaB samples and would offer a broader variety of reference samples for validation.

**Comment by roryk** [comment]
Sorry for taking so long to get back to you, I just had a kid so I've been wrapped up in that. This is a good suggestion.

Writing how to do it here in case you or someone else wants to tackle it since this is pretty straightforward. This is just needs us to follow one of the GIAB cloudbiolinux recipes. These two samples are the mother and father of a sample we already install validation calls from, that recipe is here for GRCh37:

https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/giab-NA24631.yaml

and here for hg38:

https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/giab-NA24631.yaml

so we'd need to make `giab-NA24694.yaml` and `giab-NA24695.yaml` in that same format. The base URL for those downloads are here:

https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG006_NA24694_father/NISTv3.3.2/
 
https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG007_NA24695_mother/NISTv3.3.2/

and then we'd just need to add `giab-NA12694` and `giab-NA24695` to here:

https://github.com/chapmanb/cloudbiolinux/blob/master/config/biodata.yaml#L37-L38

and here:

https://github.com/chapmanb/cloudbiolinux/blob/master/config/biodata.yaml#L37-L38

and that should install them.

**Comment by naumenko-sa** [comment]
Hi!

Thanks @roryk  for the roadmap!

I added them: https://github.com/chapmanb/cloudbiolinux/pull/347

@sam-ber please update
`nohup bcbio_nextgen.py upgrade -u skip --data --genomes hg38`
and let us know how it works!

We will be happy to publish bcbio validation results with these data in the docs, if you have some and want to contribute.

SN

**Comment by sam-ber** [comment]
Hi,
thank you very much for your effort @roryk and @naumenko-sa !

Unfortunately we would also need this addition for GRCh37, so I tried to open a PR (for the cloudbiolinux repo), which was denied as I do not have any permission to do so.
As of this moment there are no validation results to be expected), since these samples were not available until now.

Would it be possible for you @naumenko-sa to either add these files also to GRCh37 or grant me (temporary) permission for the cloudbiolinux repository to open PRs?
Many thanks again.

**Comment by naumenko-sa** [comment]
Hi @sam-ber !

I hope there is no need in a special permission to open a PR.

1. fork https://github.com/chapmanb/cloudbiolinux into your git account and then 
2. clone locally
3. set upstream
4. create a branch
5. add recipies
6. commit recipies
7. push changes to your fork
8. create a PR from your github web interface

The workflow is described here: https://github.com/hbc/knowledgebase/blob/master/misc/git.md
and elsewhere.

It might take some time to master this, but once you are done, you could contribute more easily to cloudbiolinux and bcbio.

S

**Comment by sam-ber** [comment]
Hi @naumenko-sa !
Thank you for your kind explanation. The necessity to first fork the original repository somehow eluded me.
Please have a look on https://github.com/chapmanb/cloudbiolinux/pull/348 and let me know if I can be of additional help in this regard.

**Comment by naumenko-sa** [comment]
merged, thanks for your contribution!
