### ISSUE TITLE
EBV missing from GDC viral sequences?

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3152]
I was wondering:
The GDC virus decoy sequences contain exactly 200 virus genomes: 
https://gdc.cancer.gov/files/public/file/GRCh83.d1.vd1_virus_decoy.txt

The bcbio viral collection only contains 199 genomes:
http://s3.amazonaws.com/biodata/viral/hg38-gdc-viral.tar.gz

EBV seems to be missing. Is there a reason for that?

**Comment by roryk** [comment]
Hi Ben,

We have EBV as an artificial chromosome in the hg38 genome since it's so common to see it during sequencing, so it will show up as zero if we quantitate to the GDC virus since it gets captured by the artificial chromosome. We weren't adding it to the virus report but in I think the 1.2.0 or 1.1.9 release we fixed it so we are now.

**Comment by gabeng** [comment]
Hi Rory,

I understand that you do not need it in hg38. I am actually using GRCh37 which seems to use the same viral sequences as hg38. In my case it would be very useful to add EBV to the viral reference.

**Comment by gabeng** [comment]
Ah, wait - I was using an old reference data volume (pre-1.1.9). Thanks for the hint - I found your commit. Sorry for troubling you.

**Comment by roryk** [comment]
Hi Ben! Thanks so much, no worries at all. We only found the EBV issue in the first place because someone commented on it. It is really helpful to have eyes on everything, so we are happy you asked!
