### ISSUE TITLE
Salmon version update

### ISSUE THREAD

**Issue by sd282** [bcbio/bcbio-nextgen#3179]
Hello,

I came across an error when I tried to process some quant.sf files (output from Salmon) on R. I got this message: 

reading in files with read_tsv
1 Error in readBin(bootCon, "integer", n = expected.n) :
  invalid 'n' argument

On doing some research, I believe this arose due to the version of Salmon that I am using which is a part of the bcbio pipeline. It seems like the version on bcbio is Salmon v0.14.1. When I ran Salmon, I did get a warning message asking me to update to Salmon1.1.0. Could you please advise me as to how I can resolve this issue? Is there a way that Salmon can be updated in bcbio?

**Comment by roryk** [comment]
Hi @sd282,

Are you running bcbio itself or just running one of the tools we installed on your own? We can't really debug issues on tools that are being run outside of bcbio. That being said, the tximport issue you are seeing is due to having an old version of tximport. See https://github.com/mikelove/tximport/issues/31 for the solution.
