### ISSUE TITLE
Installing without Anaconda

### ISSUE THREAD

**Issue by mboisson** [bcbio/bcbio-nextgen#3351]
Hi,
Installing Anaconda is not recommended on Compute Canada clusters, as it comes with a lot of issues : 
https://docs.computecanada.ca/wiki/Anaconda

Can there be instructions to install the pipeline without Anaconda ? Most bioinformatics tools are already installed as modules, and we do not want users to reinstall things like bowtie...

**Comment by roryk** [comment]
Hi Maxime,

Sorry about that, it would be awesome to be able to not have to install extra copies of tools, but practically it is not possible to do that unfortunately. There is no way for us to support user-installed versions of tools because we will run into endless issues where tools are out of date or incompatible with each other, and debugging issues will be a nightmare. There's like 300 bioconda packages that get installed with bcbio so you can imagine the scale of the problem.

You can install bcbio for everyone to use so there is only one extra copy of the tools, usually we have bcbio installed as a module so folks can just load it. The tool directory has a lot of tools in it, but space-wise it is not huge, 60G, about the size of a small NGS project.

Hope that helps get you going!

**Comment by mboisson** [comment]
It does not really help us going, no. How about just providing a container that users can use with singularity then. If you are worried about reproducibility, conda really is not shining for that.

**Comment by mboisson** [comment]
Conda simply is not an option for us, so that means our users can't use your software.

**Comment by roryk** [comment]
Hi Maxime,

Sorry about not being able to cover your use case-- we do have docker containers for a subset of the analyses (https://github.com/bcbio/bcbio_docker) but it doesn't include everything supported in bcbio unfortunately. FWIW bcbio does an isolated conda install, so you don't need to make conda itself generally available to users, it installs everything into its own contained environment.

**Comment by mboisson** [comment]
Even assuming it is self-contained, it still duplicates a lot of files and uses a lot of space.  60GB is larger than very large commercial software such as Matlab.

**Comment by roryk** [comment]
Hi Maxime,

Yup, I agree-- it is definitely not ideal to duplicate but this is a massive thing to maintain for free, so we have to make some concessions in order to make it possible-- letting bioconda handle the installation and version management was one of them. Sorry that it seems like bcbio is a no-go on your compute, we try to make it available for as many folks are possible but there are edge cases that we just can't handle.

**Comment by mboisson** [comment]
Thanks. I will tell my user to look for alternatives, or see whether the containers can address their need then.
