### ISSUE TITLE
Q: Output variants of population variant calling with GATK

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3356]
I have 75 affected individuals and I tried to variant call all of them together placing them in the same batch. This yielded a final VCF file for all samples. 

From a previous study, I know for sure that 5 of them have a specific validated variant which does NOT appear in the final VCF file (I can clearly see the HET variant in those 5 samples using IGV and their BAM files).

The question is: Why I cannot see this variant in the final VCF? Can I set a parameter to allow the output of ALL variants detected in each sample?

Thank you for your support,
KK

**Comment by roryk** [comment]
Hi Konstantinos,

It's tough to say without having the data to look at, is there any way you could slice out a region of around 1000 bases from the BAM files, the gVCF files and the VCF files so we can take a look?

**Comment by kokyriakidis** [comment]
I will try! But first let me ask you something that I just noticed:

Q1) The variant I am referring to is in position chr12:106992962 but the region in the bed file starts from chr12:106992964! This could be one reason it missed it? Is there a way to add some padding while running GATK?

Q2) Normally, this variant calling approach (calling in the same batch) should produce a VCF file with ALL variants from ALL samples? Will it include variants that appear in only 1-2 samples? Or there is a cut-of?

**Comment by roryk** [comment]
Hi @kokyriakidis,

Good detective work. No need for the files, that is definitely the problem-- if you are using that BED file for the `variant_regions` option, it will only call variants in those regions so it should miss the variant you are looking at. The reason why we recommend to use `variant_regions` with capture kits is because outside of the intended capture regions there will be a large amount of false positives. You can expand the regions in the BED file in both directions by some bases if you want to try to look in regions adjacent to where you are looking with `bedtools slop`, but be warned you might have a higher-than-normal false positive rate in those regions.

The other thing I would check is if the BED file you are using is against the correct version of the genome. Is it for hg38 or GRCh37? If it is the wrong one, that might be why the coordinates aren't overlapping your region.

Yes, the variant calling approach should have all variants in it. There isn't a cutoff. The idea is that for every spot there is a variant called in any of the variant files, there should be a record of if its homozygous reference or no-call across all of the samples.

**Comment by kokyriakidis** [comment]
Hi @roryk !

Is there a way to disable annotation with vcfanno? I want a clean vcf file without any annotation. Not even dbsnp.

**Comment by roryk** [comment]
Hi @kokyriakidis,

Sorry about taking so long to respond, I have a little bit of a backlog of bcbio stuff that I'm just getting to. We don't have a way to shut it off-- if you need to strip the annotation you can do it with bcftools at the end though:

```bash
bcftools annotate -x INFO your-vcf-file
```

will strip all of the INFO fields off. Hope that helps get you where you need to be at!
