### ISSUE TITLE
bcbioRNASeq update

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3515]
Is it possible to move r-bcbiornaseq to a new R >= 4.0 environment so it can update properly? 

Running an analysis with hg19 in bcbio with tools_on: [bcbiornaseq] produces an bcbioRNASeq object but for some reason uses GRCh38 annotation. This must be a bug due to the very old version of r-bcbiornaseq (v0.2.9 instead of v0.3.41)

**Comment by naumenko-sa** [comment]
Hi!

bcbiornaseq is changing very fast which is hard for production environments to adapt to, that's why we pinned it to the old version.
I think it operates on gene counts level agnostic of the reference genome. If hg19 is not working for you in RNA-seq, maybe just switch to hg38? Again, it is not variant calling where variant coordinates are different, in RNA-seq you get counts for the same genes, just the annotation in hg38 will be more fresh.

We are switching to Gencode-38/Ensembl-104 in bcbio1.2.9.

We consider unpinning bcbiornaseq (and pinning it again to the more fresh version), but that won't happen in 1.2.9.

You also might use bcbioRNAseq post-bcbio - just import the counts.

Sergey

**Comment by naumenko-sa** [comment]
updated in the latest dev, please check out
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L272

**Comment by naumenko-sa** [comment]
updated in the bcbio 1.2.9 release.
