### ISSUE TITLE
Avoiding to download dbSNP

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3528]
For various reasons I had to update data installations a few times in the past weeks. 
Is there a way to avoid download and indexing of dbSNP? The storage space consumption is considerable and indexing takes ages. I am not using dbSNP in annotations anyway (#3388).

Regards,
Ben

**Comment by naumenko-sa** [comment]
Hi Ben @gabeng !

I think you may try to imitate having dbSNP database in `hg38/variation`.
Touch the output files: https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/dbsnp.yaml

If place a small fake vcf there.

dbSNP is tightly integrated with the cancer variant calling pipeline, so we can't get easily rid of it.

I hope you are aware of `--nodata` installation and linking the old data folder, since it changes not very often. This allows to avoid unnesessary data downloads. https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html#creating-a-separate-bcbio-installation

SN

**Comment by gabeng** [comment]
Hi Sergey,

I tried the first suggestion. The ggd recipe is downloaded every time `bcbio_nextgen.ps upgrade` is started and initiates download of the dbsnp vcf via wget. I was not able to fake the completed dbsnp download so far. Maybe I interrupted at the wrong time. I will try that further.
Usually I use the `--nodata` option, but recently I was testing tools that required additional data like `kraken`, and I noticed that my GiaB data was outdated. 

Thanks for your help!

Ben
