### ISSUE TITLE
Update in cloudbiolinux enviroments - please test out!

### ISSUE THREAD

**Issue by YM-Chuang** [bcbio/bcbio-nextgen#3538]
Greeting,

Recently, I am trying the installation of bcbio 1.2.8 with following command.
"python3 bcbio_nextgen_install.py /home/bcbio --tooldir=/home/bcbio/tools/ --nodata"

I have tried many times, but it always stuck in solving environment (More than ~30hrs). 

And I realized conda didn't take a lot of memory from my computer, it only take ~8GB (while I still have ~32GB in free and ~24GB in buff/cache)

The only one error I have before solving environment is:
 - package arriba-1.0.1-h10824c4_0 requires htslib >=1.8,<1.9.0a0, but none of the providers can be installed

I apologized that I am not familiar with Linux and Python. 
Seek for your help and thank you in advance.

**Comment by naumenko-sa** [comment]
I reproduced the issue, there are indeed dependency solving problems.
I passed the first one with
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L19
since the older arriba required older htslib hence the stall.

We can't update to the 2x arriba - we need to update to the latest STAR first.

There are some other dependency issues downstream: libtiff, tomli.

SN
