### ISSUE TITLE
Instructions for setting up bcbio via conda

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3542]
Hi,
Sorry to keep bothering you on bcbio issues. 
I am attempting to install bcbio on a server hosted by an external organization, but ran into an issue where the SHA checksum did not match for files downloaded by the bcbio_nextgen_install.py installer.

The engineer at the organization discovered the bcbio in conda
https://anaconda.org/bioconda/bcbio-nextgen

which I was able to install.

However, I don't know how to install the genomes, as well as bwa & star aligner because on attempting to run the upgrade command, the error states that it "cannot update data for bcbio-nextgen not installed by installer".

May I have the steps to set up bcbio properly via this conda installation? As it stands, I don't think I'll be able to install bcbio via the "normal" way. Thank you.

(bcbio128) [simngl@hpc-login01 ~]$ bcbio_nextgen.py upgrade -u skip --genomes GRCh37 --genomes hg38 --aligners bwa --aligners star
Upgrading bcbio
Upgrading bcbio-nextgen data files
Traceback (most recent call last):
  File "/home/users/astar/gis/simngl/.conda/envs/bcbio128/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/users/astar/gis/simngl/.conda/envs/bcbio128/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/users/astar/gis/simngl/.conda/envs/bcbio128/lib/python3.6/site-packages/bcbio/install.py", line 350, in upgrade_bcbio_data
    data_dir = _get_data_dir()
  File "/home/users/astar/gis/simngl/.conda/envs/bcbio128/lib/python3.6/site-packages/bcbio/install.py", line 327, in _get_data_dir
    raise ValueError("Cannot update data for bcbio-nextgen not installed by installer.\n"
ValueError: Cannot update data for bcbio-nextgen not installed by installer.
bcbio-nextgen needs to be installed inside an anaconda environment
located in the same directory as the `genomes` directory.

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !

bcbio is much more than just one python package, the full nodata deployment has 
- bcbio's own conda
- bcbio-nextgen python package
- many packages in several environments specified here:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
- `tools/bin` dir with symlinks to various tools in the environments

So, unfortunately, you can't install bcbio python package and then install data from it - you'd need to run the installer.
The checksums issue was likely due to conda or proxy caches. 

SN
