### ISSUE TITLE
One failed sample causes the entire pipeline to crash

### ISSUE THREAD

**Issue by kmfisch** [bcbio/bcbio-nextgen#3552]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8
- OS name and version (`lsb_release -ds`): "CentOS Linux release 8.1.1911 (Core) "

**To Reproduce**
Exact bcbio command you have used: 

```
bcbio_nextgen.py /expanse/projects/qstore/csd686/kfisch/sample_sheet_new.yaml \
-n 64 \
-t local \
--workdir /expanse/projects/qstore/csd686/kfisch/
```

Your sample configuration file: attached

[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/7478020/bcbio-nextgen.log)

**Observed behavior**
Error message or bcbio output: Running the ATACseq pipeline, one of the several samples failed at the MACS2 step as the bam file wasn't properly formed. This resulted in a non-zero exit status of BCBIO that I can't move past with this one failed sample. 
```

```
![kfisch_login02__expanse_projects_qstore_csd686_kfisch_log](https://user-images.githubusercontent.com/5123063/140409229-78d09b2a-1627-4ec7-a2c5-ccb78afbb6d5.jpg)

[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/7478017/bcbio-nextgen-commands.log)
**Expected behavior**
I expected that a single failed sample would throw the error that I observed, get flagged in an error report so I know this sample failed and then would be skipped so the rest of the samples/pipeline could finish. 

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
Thank you!

**Comment by naumenko-sa** [comment]
Hi @kmfisch 

Thanks for reporting and sorry about the issues!

You are running bcbio 1.2.8, so your issue is not related to the latest big update.

Could you please attach your yaml config file?

Also, what is your macs2 version? (macs2 --version)

Thanks!
Sergey

**Comment by kmfisch** [comment]
Hi @naumenko-sa Thank you! Attached is the yaml config file. I'm running MACS2 2.2.7.1. I dug deep into this and it was a low reads file that didn't have any reads aligned in the *-DN.bam. So the fact that this file had 0 reads is expected, but what what unexpected is that instead of skipping it or throwing a warning in the log that this had 0 reads and was being skipped, it crashed the entire 
[sample_sheet_new.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/7586019/sample_sheet_new.yaml.txt)
pipeline. Thank you!

Katie

**Comment by naumenko-sa** [comment]
Hi Katie @kmfisch !

Thanks for the excellent work debugging!
I agree, we should at least give an error message in such a case.
I pushed a fix here: https://github.com/bcbio/bcbio-nextgen/pull/3562.

As a rule of thumb, we are trying to error out on the bad data in bcbio - to make this fact known as early as possible
rather than handling exceptions and proceeding.

You are on bcbio1.2.8, but if you could install a separate latest dev bcbio and test out this commit - that would be a great help.

How to install a separate bcbio:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html#creating-a-separate-bcbio-installation

Or if you could share fastq files for the failed samples (are they just empty or have some reads?) that would also be helpful.

Sergey
