### ISSUE TITLE
Can I use sentieon minimap2 to replace minimap2 in alignment with bcbio-nextgen?

### ISSUE THREAD

**Issue by jxshi** [bcbio/bcbio-nextgen#3577]
Hi guys,

Just a simple question. I noticed that the latest ```bcbio-nextgen``` pipeline has already included ```sentieon``` and ```minimap2``` in the toolsets. Can I use ```sentieon minimap2``` as aligner in the alignment process? Is there any guide on how to use this tool?

Thank you in advance!

Best,
Jianxiang

**Comment by naumenko-sa** [comment]
Hi @jxshi !

Sentieon (https://www.sentieon.com/company/) was once evaluated in bcbio and not used much since. It would be likely more productive  to use sentieon wrappers and cloud tools to run sentieon analyses rather than from bcbio.

What we have is just:
- https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/sentieon.py
- https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/ngsalign/bwa.py#L93

Sergey

**Comment by naumenko-sa** [comment]
NY clean-up!
