### ISSUE TITLE
hg38 transcripts update

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3611]
Hi @naumenko-sa !

Is there a reason that hg38 transcripts are not updated to the latest release?

**Comment by naumenko-sa** [comment]
Hi @kokyriakidis !

You can start using the latest transcriptome today with: `transcriptome_gtf` and `transcriptome_fasta`.
The analysts who needed the latest transcriptome were doing it all the way.

We were holding the transcriptome update for a long time, 
because when running a large production, 
one would better have a consistent genome + transcriptome annotation, rather than a set of upgrades.

We have evaluated TSL3 transcript level (taking levels 1-3 from Ensembl) and will likely switch to it in the next release.

Also, there is an interesting development of the last years:
https://uswest.ensembl.org/info/genome/genebuild/mane.html

Sergey

**Comment by kokyriakidis** [comment]
Thank you very much for the info!
