### ISSUE TITLE
Arriba pinned

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3613]
Hi!

Why bcbio has arriba pinned to v1.2.0?

```
# Installing into conda environment r35: arriba=1.2.0, r-base=3.5.1, r=3.5.1

```

**Comment by naumenko-sa** [comment]
Hi!

Thanks, a good point!

In brief, we are still pinning STAR
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L131
because production users were not comfortable switching to a newer one due to some issues + need of extensive validation, and because of the need to rebuild indices
https://github.com/alexdobin/STAR/issues
https://github.com/bcbio/bcbio-nextgen/issues/2693

So we cannot use the latest arriba 2.x which requires STAR > 2.7.6a

To minimize issues caused by solving arriba 1.2.0 we put it in a separate environment:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L265

The way forward here is to solve https://github.com/bcbio/bcbio-nextgen/issues/2693:
test/validate the alignments and counts generated based on the latest STAR, 
update and test the installation, and the whole RNA-seq pipeline.

When STAR is unpinned, we would be able to unpin ARRIBA.

Sergey

**Comment by kokyriakidis** [comment]
Thanks again for the detailed answer!
