### ISSUE TITLE
Does bcbio support smooth restart when a job is stopped?

### ISSUE THREAD

**Issue by lovebaboon1989** [bcbio/bcbio-nextgen#3717]
Hi there,
I'm running bcbio-nextgen on our institution's cluster server, since I have many samples for bulkRNA processing (fastq files to gene count matrix) but the usage duration for one job on the cluster is limited (5 days), I just wonder if bcbio can continue the pipeline smoothly after one job is exited and restarted after 5 days?
Many thanks!

**Comment by sjhosui** [comment]
Hi,

Yes, bcbio-nextgen tracks provenance so it can see what was most recently generated and resume from that point.

Depending on how your cluster is set up, you might also consider splitting your bulk RNA-seq samples into smaller batches for processing and then merging the count matrices at the end.


From: lovebaboon1989 ***@***.***>
Date: Thursday, October 12, 2023 at 4:45 PM
To: bcbio/bcbio-nextgen ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bcbio/bcbio-nextgen] Does bcbio support smooth restart when a job is stopped? (Issue #3717)

Hi there,
I'm running bcbio-nextgen on our institution's cluster server, since I have many samples for bulkRNA processing (fastq files to gene count matrix) but the usage duration for one job on the cluster is limited (5 days), I just wonder if bcbio can continue the pipeline smoothly after one job is exited and restarted after 5 days?
Many thanks!

**Comment by lovebaboon1989** [comment]
Hi, thanks a lot for the quick reply, that helps really a lot!
